import {
  CheckpointSnapshot,
  SideBySideDiff,
  EngineeringStoryCard,
  EvolutionQA,
} from './time-machine-types';

export const MOCK_CHECKPOINTS: CheckpointSnapshot[] = [
  {
    id: 'chk-1',
    commitSha: 'a1b2c3d',
    versionTag: 'v1.0.0',
    timestamp: 'March 15, 2024',
    authorName: 'Elena Rostova',
    message: 'feat: initial monolithic AuthGateway & REST API release',
    totalLines: 14200,
    cyclomaticComplexity: 4.2,
    techDebtHours: 8,
    p95LatencyMs: 14.5,
    securityScore: 98,
    healthScore: 98.0,
    nodeCount: 12,
    edgeCount: 18,
    eventCategory: 'release',
  },
  {
    id: 'chk-2',
    commitSha: 'e4f5g6h',
    versionTag: 'v1.4.2',
    timestamp: 'May 20, 2024',
    authorName: 'Sarah Chen',
    message: 'feat: add Redis cluster caching layer for session tokens under ADR-0012',
    totalLines: 22400,
    cyclomaticComplexity: 6.8,
    techDebtHours: 14,
    p95LatencyMs: 8.2,
    securityScore: 96,
    healthScore: 96.5,
    nodeCount: 24,
    edgeCount: 38,
    eventCategory: 'adr',
  },
  {
    id: 'chk-3',
    commitSha: 'i7j8k9l',
    versionTag: 'v2.0.0',
    timestamp: 'July 10, 2024',
    authorName: 'Marcus Vance',
    message: 'refactor: PaymentService checkout optimization (35% P95 latency drop)',
    totalLines: 38900,
    cyclomaticComplexity: 9.4,
    techDebtHours: 22,
    p95LatencyMs: 24.5,
    securityScore: 94,
    healthScore: 94.0,
    nodeCount: 42,
    edgeCount: 68,
    eventCategory: 'refactor',
  },
  {
    id: 'chk-4',
    commitSha: 'm0n1o2p',
    versionTag: 'v3.1.0',
    timestamp: 'September 05, 2024',
    authorName: 'Elena Rostova',
    message: 'arch: migrate payment processing to Strimzi Kafka microservice event bus',
    totalLines: 64100,
    cyclomaticComplexity: 12.1,
    techDebtHours: 32,
    p95LatencyMs: 18.2,
    securityScore: 95,
    healthScore: 93.5,
    nodeCount: 78,
    edgeCount: 124,
    eventCategory: 'migration',
  },
  {
    id: 'chk-5',
    commitSha: 'q3r4s5t',
    versionTag: 'v4.0.0',
    timestamp: 'December 18, 2024',
    authorName: 'Alex Rivera',
    message: 'feat: rapid feature expansion (tech debt spike due to inline SQL queries)',
    totalLines: 98400,
    cyclomaticComplexity: 18.4,
    techDebtHours: 42,
    p95LatencyMs: 180.0,
    securityScore: 88,
    healthScore: 82.0,
    nodeCount: 112,
    edgeCount: 194,
    eventCategory: 'incident',
  },
  {
    id: 'chk-6',
    commitSha: 'u6v7w8x',
    versionTag: 'v4.8.0',
    timestamp: 'August 06, 2026',
    authorName: 'Staff AI Reviewer',
    message: 'refactor: CodeAtlas AI Engineering OS clean architecture refactoring',
    totalLines: 124500,
    cyclomaticComplexity: 7.2,
    techDebtHours: 24,
    p95LatencyMs: 24.2,
    securityScore: 100,
    healthScore: 96.0,
    nodeCount: 148,
    edgeCount: 260,
    eventCategory: 'release',
  },
];

export const MOCK_SIDE_DIFF: SideBySideDiff = {
  baseSha: 'a1b2c3d (v1.0.0 March 2024)',
  headSha: 'u6v7w8x (v4.8.0 August 2026)',
  baseVersion: 'v1.0.0',
  headVersion: 'v4.8.0',
  addedServices: [
    'PaymentIngressWorker (gRPC)',
    'StripeAdapterMicroservice',
    'KafkaEventBroker Cluster',
    'Neo4j Cypher Graph Engine',
  ],
  removedServices: [
    'MonolithicSyncCheckoutHandler',
    'LegacyInMemSessionMap',
  ],
  modifiedRelationships: [
    'AuthGateway -> RedisCacheCluster (L2 Token Caching)',
    'PaymentService -> Kafka (Async Event Topic)',
  ],
  techDebtDeltaHours: +16,
  latencyDeltaMs: +9.7,
  securityDeltaRating: '+2 pts (98 -> 100 SOC2 Compliant)',
  aiComparisonSummary: 'System evolved from a 12-node monolithic REST prototype into a 148-node event-driven microservice architecture with zero layer bypasses.',
};

export const MOCK_STORY_CARDS: EngineeringStoryCard[] = [
  {
    id: 'story-1',
    date: 'March 2024',
    milestoneTitle: 'Authentication Service & REST API Core Introduced',
    category: 'architecture',
    summary: 'Initial core prototype launched with basic JWT auth router and single PostgreSQL instance.',
    impactMetrics: '14.2k LOC • 12 Nodes • 14.5ms P95',
    sourceCommitSha: 'a1b2c3d',
  },
  {
    id: 'story-2',
    date: 'May 2024',
    milestoneTitle: 'Redis Cache Cluster Introduced under ADR-0012',
    category: 'cache',
    summary: 'Session token validation offloaded to Redis, reducing database read lock contention.',
    impactMetrics: 'Latency dropped to 8.2ms P95',
    sourceCommitSha: 'e4f5g6h',
  },
  {
    id: 'story-3',
    date: 'September 2024',
    milestoneTitle: 'Asynchronous Kafka Event Bus Migration',
    category: 'microservice',
    summary: 'Synchronous REST checkout decoupled via Strimzi Kafka event stream.',
    impactMetrics: '100% Zero Data Loss Event Processing',
    sourceCommitSha: 'm0n1o2p',
  },
  {
    id: 'story-4',
    date: 'December 2024',
    milestoneTitle: 'Technical Debt Spike & Inline Query Coupling',
    category: 'tech_debt',
    summary: 'Rapid feature rollout caused cyclomatic complexity spike (18.4) and 42 hours of technical debt.',
    impactMetrics: 'Tech Debt spiked to 42h',
    sourceCommitSha: 'q3r4s5t',
  },
  {
    id: 'story-5',
    date: 'August 2026',
    milestoneTitle: 'Clean Hexagonal Architecture Refactored by Staff AI',
    category: 'performance',
    summary: 'Monolithic class decomposition restored overall health score from 82.0 to 96.0.',
    impactMetrics: 'Health 96.0 • Tech Debt reduced by 18h',
    sourceCommitSha: 'u6v7w8x',
  },
];

export const MOCK_EVOLUTION_QA: EvolutionQA[] = [
  {
    id: 'qa-1',
    question: 'Show architecture six months ago (February 2026)',
    answerSummary: 'Six months ago, the system contained 112 nodes with elevated PaymentService cyclomatic complexity (18.4) before Staff AI refactoring.',
    targetTimestamp: 'February 2026',
    evidenceSha: 'q3r4s5t',
    confidencePct: 98.6,
  },
  {
    id: 'qa-2',
    question: 'When did coupling increase and technical debt spike?',
    answerSummary: 'Technical debt spiked in December 2024 (v4.0.0) during rapid checkout feature expansion when inline SQL queries were written inside PaymentService.',
    targetTimestamp: 'December 2024',
    evidenceSha: 'q3r4s5t',
    confidencePct: 99.2,
  },
];
