import { ReleaseCandidate } from './release-types';

export const MOCK_RELEASE_CANDIDATES: ReleaseCandidate[] = [
  {
    id: 'rc-v480-2',
    name: 'v4.8.0-rc2: Enterprise Async Checkout & Multi-Tenant Partitioning',
    version: '4.8.0-rc2',
    targetEnvironment: 'production',
    author: {
      name: 'Elena Rostova',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      role: 'Staff Release Architect',
    },
    gitBranch: 'release/v4.8.0',
    commitHash: 'a4f9b21e',
    createdAt: '12 mins ago',

    scorecard: {
      readinessScore: 96,
      deploymentRisk: 'LOW',
      architectureHealthPct: 94,
      performancePredictionMs: 24.2,
      securityReadinessPct: 100,
      techDebtDeltaHours: -18,
      breakingChangeRiskCount: 0,
      repositoryHealthPct: 98,
      rollbackConfidencePct: 99.2,
      overallAiConfidencePct: 99.6,
    },

    timelineStages: [
      {
        id: 'planning',
        name: 'Stage 1: Architecture Planning & ADR Review',
        description: 'Evaluated ADR-0042 hybrid graph-relational trade-offs.',
        status: 'COMPLETED',
        startedAt: '09:00 AM',
        completedAt: '09:15 AM',
        duration: '15m',
        aiRecommendation: 'ADR-0042 approved by Architecture Council. Zero governance drift detected.',
        evidenceItems: ['ADR-0042 verified', 'Domain context boundary locked'],
      },
      {
        id: 'development',
        name: 'Stage 2: Code Generation & Commit Ingestion',
        description: 'Merged 48 files across PaymentService, AuthRouter, and Alembic migrations.',
        status: 'COMPLETED',
        startedAt: '09:15 AM',
        completedAt: '10:30 AM',
        duration: '1h 15m',
        aiRecommendation: 'All TypeScript and Python FastAPI modules compiled without type warnings.',
        evidenceItems: ['Tree-Sitter AST parsed 1,420 symbols', 'Git commit deltas ingested'],
      },
      {
        id: 'review',
        name: 'Stage 3: AI Code Review & Intent Audit',
        description: 'Staff AI Code Reviewer executed correctness, security, and performance audits.',
        status: 'COMPLETED',
        startedAt: '10:30 AM',
        completedAt: '10:45 AM',
        duration: '15m',
        aiRecommendation: '1 Critical SQL injection finding resolved with parameterized SQLAlchemy update statement.',
        evidenceItems: ['PR #482 Approved', 'OWASP Top 10 Audit Passed'],
      },
      {
        id: 'testing',
        name: 'Stage 4: Automated Integration & DeepEval Suite',
        description: 'Ran 42 unit tests, Playwright browser E2E tests, and DeepEval AI benchmarks.',
        status: 'COMPLETED',
        startedAt: '10:45 AM',
        completedAt: '11:05 AM',
        duration: '20m',
        aiRecommendation: '100% test suite pass rate with 88.4% code coverage.',
        evidenceItems: ['42 pytest cases passed', '0 regression failures'],
      },
      {
        id: 'simulation',
        name: 'Stage 5: Simulation Studio Stress Test',
        description: 'Simulated 100k peak user traffic spike Monte Carlo load test.',
        status: 'COMPLETED',
        startedAt: '11:05 AM',
        completedAt: '11:20 AM',
        duration: '15m',
        aiRecommendation: 'P95 response latency dropped from 340.5ms to 24.2ms. Redis memory stable at 1.2GB.',
        evidenceItems: ['100k Peak Traffic Sim completed', '0 memory leaks detected'],
      },
      {
        id: 'approval',
        name: 'Stage 6: Multi-Signoff Approval Gate',
        description: 'Signoffs granted by Principal Architect, CISO, and SRE Lead.',
        status: 'COMPLETED',
        startedAt: '11:20 AM',
        completedAt: '11:25 AM',
        duration: '5m',
        aiRecommendation: 'Pre-deployment readiness score 96/100. Safe to initiate canary rollout.',
        evidenceItems: ['Sarah Chen approved', 'Marcus Vance approved'],
      },
      {
        id: 'deployment',
        name: 'Stage 7: Istio 90/10 Canary Split Deployment',
        description: 'Rrouting 10% production traffic to v4.8.0-rc2 canary pods in US-East-1.',
        status: 'IN_PROGRESS',
        startedAt: '11:25 AM',
        duration: 'Live (5m)',
        aiRecommendation: 'Canary error rate 0.00% across 14,200 requests. Proceeding to 50/50 split.',
        evidenceItems: ['Istio virtual service routing active', '0 HTTP 5xx errors'],
      },
      {
        id: 'monitoring',
        name: 'Stage 8: Real-Time Telemetry & Tracing Audit',
        description: 'Monitoring Prometheus latency metrics and OpenTelemetry trace traces.',
        status: 'PENDING',
        startedAt: 'Pending Stage 7',
        duration: 'Est. 10m',
        aiRecommendation: 'Continuous health monitoring armed.',
        evidenceItems: ['Prometheus alerting active'],
      },
      {
        id: 'validation',
        name: 'Stage 9: Automated Post-Deployment Verification',
        description: 'Validating database migration indexes and multi-tenant row security policies.',
        status: 'PENDING',
        startedAt: 'Pending Stage 8',
        duration: 'Est. 5m',
        aiRecommendation: 'Synthetic user transaction probes queued.',
        evidenceItems: ['Synthetic transaction probe ready'],
      },
      {
        id: 'rollback',
        name: 'Stage 10: Automatic Rollback Strategy Standby',
        description: 'Automated Helm rollback & Istio traffic drain on standby.',
        status: 'PENDING',
        startedAt: 'Standby',
        duration: '0m',
        aiRecommendation: 'Rollback plan confidence 99.2%. Estimated MTTR recovery 1.8 minutes.',
        evidenceItems: ['Helm release v4.7.9 cached', 'Rollback script armed'],
      },
    ],

    serviceRiskNodes: [
      {
        serviceId: 'svc-payment',
        serviceName: 'Payment Microservice (svc-payment-core)',
        tier: 'tier-1',
        riskScore: 12,
        riskLevel: 'LOW',
        failurePropagationImpact: 'Isolated via Kafka event buffer; 0 impact on checkout availability.',
        dependencies: ['svc-auth', 'db-postgres', 'queue-kafka'],
        status: 'STRESS_TESTED',
      },
      {
        serviceId: 'svc-auth',
        serviceName: 'Auth & Identity Router (svc-auth-router)',
        tier: 'tier-1',
        riskScore: 8,
        riskLevel: 'LOW',
        failurePropagationImpact: 'Stateless JWT validation; zero database write load.',
        dependencies: ['cache-redis'],
        status: 'HEALTHY',
      },
      {
        serviceId: 'db-postgres',
        serviceName: 'PostgreSQL Relational DB (db-primary)',
        tier: 'tier-1',
        riskScore: 14,
        riskLevel: 'LOW',
        failurePropagationImpact: 'Alembic migration 0042 is backward compatible with zero lock wait time.',
        dependencies: [],
        status: 'HEALTHY',
      },
      {
        serviceId: 'queue-kafka',
        serviceName: 'Kafka Event Broker (strimzi-kafka-cluster)',
        tier: 'tier-1',
        riskScore: 10,
        riskLevel: 'LOW',
        failurePropagationImpact: 'Replicated topic payment.checkout.v1 across 3 availability zones.',
        dependencies: [],
        status: 'HEALTHY',
      },
    ],

    preDeploymentDeltas: [
      {
        category: 'Database Schema',
        beforeState: 'Un-indexed payment status queries taking 340ms',
        afterState: 'Alembic 0042 composite index added (repo_id, status, created_at)',
        riskAssessment: 'Safe backward-compatible DDL schema migration.',
        impactLevel: 'SAFE',
      },
      {
        category: 'API Routing',
        beforeState: 'Synchronous blocking HTTP requests to external Stripe API',
        afterState: 'Asynchronous FastAPI non-blocking worker with Kafka event producer',
        impactLevel: 'SAFE',
        riskAssessment: 'Drops P95 latency from 340ms to 24ms.',
      },
      {
        category: 'Architecture Drift',
        beforeState: '1 Layer Bypass detected in PaymentService',
        afterState: '0 Bypasses (Clean Hexagonal Repository Pattern)',
        impactLevel: 'SAFE',
        riskAssessment: 'Fully restores domain boundary isolation.',
      },
    ],

    rollbackPlan: {
      planId: 'rollback-v480-2',
      estimatedRecoveryTimeMinutes: 1.8,
      affectedServices: ['svc-payment-core', 'svc-auth-router'],
      riskAnalysis: 'Low rollback risk. Database migration 0042 is strictly additive and non-destructive; rollback does not require column drops.',
      rollbackOrder: [
        {
          stepNumber: 1,
          action: 'Drain Istio Canary Traffic',
          targetService: 'istio-virtualservice-payment',
          commandSnippet: 'kubectl apply -f k8s/istio-route-drain-100-v4.7.yml',
          estimatedDurationSec: 15,
          automated: true,
        },
        {
          stepNumber: 2,
          action: 'Rollback Helm Release to v4.7.9',
          targetService: 'svc-payment-core',
          commandSnippet: 'helm rollback codeatlas-payment-svc 479',
          estimatedDurationSec: 45,
          automated: true,
        },
        {
          stepNumber: 3,
          action: 'Demote Alembic DB Revision to 0041',
          targetService: 'db-primary',
          commandSnippet: 'alembic downgrade 0041',
          estimatedDurationSec: 30,
          automated: true,
        },
        {
          stepNumber: 4,
          action: 'Verify Health Probes & Tracing Telemetry',
          targetService: 'all-tier-1-services',
          commandSnippet: 'curl -f http://payment-svc/health/readiness',
          estimatedDurationSec: 18,
          automated: true,
        },
      ],
      alternativeRecoveryOptions: [
        {
          strategyName: 'Strategy A (Recommended): Automated Helm & Istio Rollback',
          description: 'Instantly revert Istio traffic routing to stable v4.7.9 pods while running background Alembic downgrade.',
          recoveryTimeMin: 1.8,
          dataLossRisk: '0% Zero Data Loss (All payment events preserved in Kafka queue)',
        },
        {
          strategyName: 'Strategy B: Circuit Breaker Fallback Mode',
          description: 'Enable Redis circuit breaker flag to route payment checkout traffic to legacy fallback gateway.',
          recoveryTimeMin: 0.5,
          dataLossRisk: '0% Zero Data Loss',
        },
      ],
      postmortemTemplate: {
        incidentTitle: 'Postmortem: Deployment Failure & Immediate Recovery for Release v4.8.0-rc2',
        rootCauseCategory: 'Third-Party Integration Timeout',
        severity: 'SEV-2 (Mitigated)',
        mitigationSummary: 'Automated SRE rollback strategy triggered via Istio 90/10 traffic drain. Full recovery achieved in 1.8 minutes.',
        preventativeActions: [
          'Increase circuit breaker timeout threshold from 2s to 5s for Stripe sandbox',
          'Add automated chaos injection test to CI pipeline',
        ],
      },
      recoveryChecklist: [
        { task: 'Verify Istio VirtualService 100% traffic shift to v4.7.9', verified: true },
        { task: 'Confirm Kafka message consumer offset lag is zero', verified: true },
        { task: 'Execute Alembic database revision check (alembic current)', verified: true },
        { task: 'Notify SRE incident slack channel #release-alerts', verified: true },
      ],
    },

    deploymentAdvice: {
      question: 'Can we deploy release candidate v4.8.0-rc2 to production today?',
      verdict: 'DEPLOY_NOW',
      deploymentRecommendation: 'DEPLOY IMMEDIATELY. Release v4.8.0-rc2 has achieved a 96/100 Readiness Score with 100% Security OWASP compliance and 0 breaking API changes. Pre-deployment simulations confirm a 92% drop in P95 latency.',
      keyEvidence: [
        'Readiness Score: 96/100 (LOW deployment risk)',
        '100k Peak User Traffic Simulation Passed (P95: 24.2ms)',
        'SQL Injection Vulnerability in PaymentService 100% Refactored',
        'Rollback Plan Confidence: 99.2% (Estimated MTTR: 1.8 mins)',
      ],
      biggestRiskFactor: 'Third-party Stripe API rate limits during peak traffic bursts (Mitigated via Kafka decoupling).',
      highestRiskService: 'svc-payment-core (Monitored via 10% Istio Canary)',
      aiConfidencePct: 99.6,
    },

    interSystemLinks: [
      { subsystem: 'mission_control', label: 'AI Mission Control', url: '/command-center', badge: 'Command' },
      { subsystem: 'cto_workspace', label: 'AI CTO Workspace', url: '/ai-cto', badge: 'CTO' },
      { subsystem: 'investigation_engine', label: 'AI Investigation Engine', url: '/investigate', badge: 'Root Cause' },
      { subsystem: 'refactoring_planner', label: 'AI Refactoring Planner', url: '/improve', badge: 'Refactor' },
      { subsystem: 'doc_engineer', label: 'AI Doc Engineer', url: '/docs', badge: 'Docs' },
      { subsystem: 'code_review', label: 'AI Code Review Intelligence', url: '/review', badge: 'Review' },
      { subsystem: 'repository_explorer', label: 'Repository Explorer', url: '/repositories', badge: 'AST' },
      { subsystem: 'architecture_intelligence', label: 'Architecture Intelligence', url: '/architecture', badge: 'Topology' },
      { subsystem: 'knowledge_graph', label: 'Knowledge Graph', url: '/knowledge', badge: 'Neo4j' },
      { subsystem: 'dependency_intelligence', label: 'Dependency Intelligence', url: '/dependency-graph', badge: 'Graph' },
      { subsystem: 'monitoring', label: 'Real-Time Monitoring', url: '/monitor', badge: 'Datadog' },
      { subsystem: 'tech_debt', label: 'Technical Debt Dashboard', url: '/tech-debt', badge: 'Debt' },
      { subsystem: 'performance', label: 'Performance & Health', url: '/health', badge: 'Metrics' },
      { subsystem: 'security', label: 'Security Center', url: '/security', badge: 'SOC2' },
      { subsystem: 'simulation_studio', label: 'Simulation Studio', url: '/simulate', badge: 'Monte Carlo' },
      { subsystem: 'copilot', label: 'AI Copilot', url: '/search', badge: 'Copilot' },
    ],
  },
];
