"""add_complexity_timeline_columns

Revision ID: 1a52090ec2ba
Revises: cf465ac050de
Create Date: 2026-07-06 18:01:40.011947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a52090ec2ba'
down_revision: Union[str, Sequence[str], None] = 'cf465ac050de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commit_snapshots', sa.Column('average_function_size', sa.Float(), nullable=False))
    op.add_column('commit_snapshots', sa.Column('cohesion_score', sa.Float(), nullable=False))
    op.add_column('commit_snapshots', sa.Column('maintainability_index', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commit_snapshots', 'maintainability_index')
    op.drop_column('commit_snapshots', 'cohesion_score')
    op.drop_column('commit_snapshots', 'average_function_size')
    # ### end Alembic commands ###
