"""create_graph_tables

Revision ID: 297e6b0e65f8
Revises: 3e4a1525d67a
Create Date: 2026-07-02 08:15:35.202954

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "297e6b0e65f8"
down_revision: Union[str, Sequence[str], None] = "3e4a1525d67a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_nodes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("repository_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_graph_nodes_id"), "graph_nodes", ["id"], unique=False)
    op.create_table(
        "graph_relationships",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("repository_id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_graph_relationships_id"), "graph_relationships", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_graph_relationships_id"), table_name="graph_relationships")
    op.drop_table("graph_relationships")
    op.drop_index(op.f("ix_graph_nodes_id"), table_name="graph_nodes")
    op.drop_table("graph_nodes")
    # ### end Alembic commands ###
