"""add_tech_debt_tables

Revision ID: 6d8235a7087a
Revises: 1a52090ec2ba
Create Date: 2026-07-07 08:28:56.714618

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d8235a7087a"
down_revision: Union[str, Sequence[str], None] = "1a52090ec2ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_scores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("repo_id", sa.String(), nullable=False),
        sa.Column("architecture", sa.Float(), nullable=False),
        sa.Column("maintainability", sa.Float(), nullable=False),
        sa.Column("testing", sa.Float(), nullable=False),
        sa.Column("documentation", sa.Float(), nullable=False),
        sa.Column("performance", sa.Float(), nullable=False),
        sa.Column("overall", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["repo_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_health_scores_id"), "health_scores", ["id"], unique=False)
    op.create_table(
        "risk_forecasts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("repo_id", sa.String(), nullable=False),
        sa.Column("prediction_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("predicted_debt", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["repo_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_forecasts_id"), "risk_forecasts", ["id"], unique=False
    )
    op.create_table(
        "technical_debt_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("repo_id", sa.String(), nullable=False),
        sa.Column("module", sa.String(), nullable=False),
        sa.Column("debt_score", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["repo_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_technical_debt_reports_id"),
        "technical_debt_reports",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_technical_debt_reports_id"), table_name="technical_debt_reports"
    )
    op.drop_table("technical_debt_reports")
    op.drop_index(op.f("ix_risk_forecasts_id"), table_name="risk_forecasts")
    op.drop_table("risk_forecasts")
    op.drop_index(op.f("ix_health_scores_id"), table_name="health_scores")
    op.drop_table("health_scores")
    # ### end Alembic commands ###
