"""add_evolution_columns

Revision ID: cf465ac050de
Revises: f0f449068de6
Create Date: 2026-07-06 17:56:20.701338

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf465ac050de"
down_revision: Union[str, Sequence[str], None] = "f0f449068de6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "commit_snapshots", sa.Column("health_score", sa.Float(), nullable=False)
    )
    op.add_column(
        "commit_snapshots", sa.Column("architecture_patterns", sa.JSON(), nullable=True)
    )
    op.add_column("commit_snapshots", sa.Column("graph_data", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("commit_snapshots", "graph_data")
    op.drop_column("commit_snapshots", "architecture_patterns")
    op.drop_column("commit_snapshots", "health_score")
    # ### end Alembic commands ###
