"""create_evolution_tables

Revision ID: f0f449068de6
Revises: 297e6b0e65f8
Create Date: 2026-07-06 17:50:57.152063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f449068de6'
down_revision: Union[str, Sequence[str], None] = '297e6b0e65f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architecture_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('alternatives', sa.String(), nullable=False),
    sa.Column('impact', sa.String(), nullable=False),
    sa.Column('related_entities', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_decisions_id'), 'architecture_decisions', ['id'], unique=False)
    op.create_table('commit_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('author_email', sa.String(), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('code_lines', sa.Integer(), nullable=False),
    sa.Column('comment_lines', sa.Integer(), nullable=False),
    sa.Column('complexity_total', sa.Integer(), nullable=False),
    sa.Column('complexity_average', sa.Float(), nullable=False),
    sa.Column('complexity_max', sa.Integer(), nullable=False),
    sa.Column('documentation_coverage', sa.Float(), nullable=False),
    sa.Column('dependencies_count', sa.Integer(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commit_snapshots_commit_sha'), 'commit_snapshots', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_commit_snapshots_id'), 'commit_snapshots', ['id'], unique=False)
    op.create_table('memory_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_snapshots_id'), 'memory_snapshots', ['id'], unique=False)
    op.create_table('repository_memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_memories_id'), 'repository_memories', ['id'], unique=False)
    op.create_table('component_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('commit_snapshot_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('complexity_total', sa.Integer(), nullable=False),
    sa.Column('complexity_average', sa.Float(), nullable=False),
    sa.Column('complexity_max', sa.Integer(), nullable=False),
    sa.Column('code_lines', sa.Integer(), nullable=False),
    sa.Column('comment_lines', sa.Integer(), nullable=False),
    sa.Column('dependencies_count', sa.Integer(), nullable=False),
    sa.Column('dependents_count', sa.Integer(), nullable=False),
    sa.Column('coupling_score', sa.Float(), nullable=False),
    sa.Column('technical_debt_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['commit_snapshot_id'], ['commit_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_snapshots_id'), 'component_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_component_snapshots_path'), 'component_snapshots', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_component_snapshots_path'), table_name='component_snapshots')
    op.drop_index(op.f('ix_component_snapshots_id'), table_name='component_snapshots')
    op.drop_table('component_snapshots')
    op.drop_index(op.f('ix_repository_memories_id'), table_name='repository_memories')
    op.drop_table('repository_memories')
    op.drop_index(op.f('ix_memory_snapshots_id'), table_name='memory_snapshots')
    op.drop_table('memory_snapshots')
    op.drop_index(op.f('ix_commit_snapshots_id'), table_name='commit_snapshots')
    op.drop_index(op.f('ix_commit_snapshots_commit_sha'), table_name='commit_snapshots')
    op.drop_table('commit_snapshots')
    op.drop_index(op.f('ix_architecture_decisions_id'), table_name='architecture_decisions')
    op.drop_table('architecture_decisions')
    # ### end Alembic commands ###
