from typing import Any, TYPE_CHECKING
from sqlalchemy import String, Text, Integer, ForeignKey, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from backend.app.models.base import Base, UUIDPrimaryKeyMixin, TimestampMixin

if TYPE_CHECKING:
    from backend.app.models.repository import Repository
    from backend.app.models.user import User


class EngineeringPlan(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    Phase 23: Persisted Engineering Plans and Roadmaps generated by AI CTO.
    Stores multi-dimensional health snapshots, prioritized work items,
    time-horizon roadmaps, source evidence citations, and version history.
    Strictly scoped to a single repository.
    """
    __tablename__ = "engineering_plans"

    repository_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("repositories.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    user_id: Mapped[str | None] = mapped_column(
        String(36),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[str] = mapped_column(
        String(50),
        default="active",
        nullable=False,
        index=True,
    )  # draft, active, completed, archived
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    time_horizon: Mapped[str] = mapped_column(
        String(50),
        default="1_month",
        nullable=False,
    )  # 1_week, 1_month, 3_months, long_term
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    health_snapshot: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    work_items: Mapped[list[dict[str, Any]] | None] = mapped_column(JSON, nullable=True)
    roadmaps: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    source_evidence: Mapped[list[dict[str, Any]] | None] = mapped_column(JSON, nullable=True)
    metadata_json: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)

    # Relationships
    repository: Mapped["Repository"] = relationship("Repository", back_populates="engineering_plans")
    user: Mapped["User | None"] = relationship("User", foreign_keys=[user_id])
