from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
)
from sqlalchemy.sql import func

from app.core.database import Base


class ArchitectureRecommendation(Base):
    """
    Persisted architecture recommendations generated by the ArchitectDecisionEngine.
    """

    __tablename__ = "architecture_recommendations"

    id = Column(String, primary_key=True, index=True)
    repo_id = Column(
        String,
        ForeignKey("repositories.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    category = Column(
        String, nullable=False
    )  # design_pattern | scalability | refactoring
    recommendation_type = Column(String, nullable=True)  # alias/field for prompt spec
    title = Column(String, nullable=False)
    description = Column(String, nullable=True)  # prompt spec description
    priority = Column(Integer, nullable=False)  # 1 (Critical) to 5 (Low)
    confidence = Column(Float, nullable=False)
    risk = Column(String, nullable=False)  # HIGH | MEDIUM | LOW
    estimated_effort = Column(String, nullable=True)
    expected_impact = Column(String, nullable=True)
    status = Column(
        String, default="open", nullable=False
    )  # open | acknowledged | dismissed
    payload = Column(JSON, nullable=True)  # Full evidence/trade-offs/reason JSON blob
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    generated_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    is_latest = Column(Boolean, default=True, nullable=False)


class ArchitectureReview(Base):
    """
    Persisted architecture reviews generated by the AI Review engine.
    """

    __tablename__ = "architecture_reviews"

    repo_id = Column(
        String,
        ForeignKey("repositories.id", ondelete="CASCADE"),
        primary_key=True,
        index=True,
    )
    health_score = Column(Float, default=100.0, nullable=False)
    strengths = Column(JSON, nullable=True)  # List of strings
    weaknesses = Column(JSON, nullable=True)  # List of strings
    summary = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class ArchitectureDecisionGenerated(Base):
    """
    Persisted Architecture Decision Records (ADRs) generated dynamically.
    """

    __tablename__ = "architecture_decisions_generated"

    id = Column(String, primary_key=True, index=True)
    repo_id = Column(
        String,
        ForeignKey("repositories.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title = Column(String, nullable=False)
    reason = Column(String, nullable=False)
    alternatives = Column(JSON, nullable=True)  # List of strings
    impact = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
