import uuid
from datetime import datetime

from sqlalchemy import (
    JSON,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)

from app.core.database import Base


class EvolutionPlanItem(Base):
    """
    Represents an individual evolution recommendation generated by ASE.
    Category: debt, architecture, dependency, security, performance, testing, documentation,
              cost, reliability, legacy, api_cleanup, database, cloud, infrastructure, plugin,
              maturity, sprint, release, roi, knowledge, compliance, quality
    """

    __tablename__ = "evolution_plan_items"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    repository_id = Column(
        String(36),
        ForeignKey("repositories.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    category = Column(String(50), nullable=False, index=True)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    target_component = Column(String(255), nullable=True)

    # Priority & Metric Scores
    priority_score = Column(Float, default=0.0, index=True)
    business_impact = Column(Float, default=0.0)
    risk_score = Column(Float, default=0.0)
    effort_score = Column(Float, default=0.0)  # 1-10 scale or estimated developer hours
    confidence_score = Column(Float, default=0.95)  # 0.0 - 1.0 confidence ratio

    # Execution & Roadmap Metadata
    target_week = Column(Integer, default=1)  # Scheduled week in evolution roadmap
    timeline_horizon = Column(
        String(50), default="next_sprint", index=True
    )  # today, next_sprint, next_quarter, next_year, ideal
    status = Column(
        String(50), default="proposed", index=True
    )  # proposed, queued, validating, approved, rejected, completed

    # ⭐ Feature 13: AI Review Board Metadata
    why_statement = Column(Text, nullable=True)
    expected_benefit = Column(Text, nullable=True)
    evidence = Column(
        JSON, default=list
    )  # List of AST snippets, log events, code references

    # ⭐ Feature 14: Improvement Dependency Graph (Prerequisites)
    prerequisites = Column(
        JSON, default=list
    )  # List of item IDs required before execution

    # ⭐ Feature 25: ROI Calculator Metrics
    roi_metrics = Column(
        JSON, default=dict
    )  # {cost_savings_usd, dev_hours_saved, bug_risk_reduction_pct}

    # Details & Payloads
    metrics = Column(JSON, default=dict)
    actions = Column(JSON, default=list)  # List of action steps or code refactors
    validation_status = Column(String(50), default="pending")  # pending, passed, failed
    risk_analysis = Column(JSON, default=dict)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class EvolutionRoadmap(Base):
    """
    Represents a multi-week phased evolution roadmap for a repository.
    """

    __tablename__ = "evolution_roadmaps"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    repository_id = Column(
        String(36),
        ForeignKey("repositories.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    title = Column(String(255), default="Autonomous Software Evolution Roadmap")
    timeframe_weeks = Column(Integer, default=4)
    overall_health_target = Column(Float, default=95.0)
    current_health_score = Column(Float, default=75.0)

    weekly_phases = Column(JSON, default=list)  # List of week phase summaries and goals
    status = Column(String(50), default="active")  # active, completed, archived

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class EvolutionAuditLog(Base):
    """
    Audit log tracking approval gateway decisions, validation execution, and automated evolutions.
    """

    __tablename__ = "evolution_audit_logs"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    repository_id = Column(String(36), nullable=False, index=True)
    item_id = Column(String(36), nullable=True)

    event_type = Column(
        String(50), nullable=False
    )  # continuous_run, validation, approval, rejection, completion
    actor = Column(String(100), default="ASE System")  # user_id or system actor
    details = Column(JSON, default=dict)

    created_at = Column(DateTime, default=datetime.utcnow)
