from enum import Enum


class GraphNodeType(str, Enum):
    REPOSITORY = "Repository"
    FOLDER = "Folder"
    FILE = "File"
    MODULE = "Module"
    CLASS = "Class"
    INTERFACE = "Interface"
    FUNCTION = "Function"
    METHOD = "Method"
    VARIABLE = "Variable"
    API_ENDPOINT = "API Endpoint"
    DATABASE_TABLE = "Database Table"
    EXTERNAL_SERVICE = "External Service"
    ENVIRONMENT = "Environment"
    DOMAIN = "Domain"
    SERVICE = "Service"
    API = "API"
    CACHE = "Cache"
    CRON_JOB = "Cron Job"
    DOCKER_SERVICE = "Docker Service"
    GITHUB_ACTION = "GitHub Action"
    COMMIT = "Commit"
    PULL_REQUEST = "Pull Request"
    ISSUE = "Issue"
    ADR = "ADR"
    DOCUMENT = "Document"
    COMMENT = "Comment"


class GraphRelationshipType(str, Enum):
    IMPORTS = "IMPORTS"
    CALLS = "CALLS"
    OWNS = "OWNS"
    IMPLEMENTS = "IMPLEMENTS"
    INHERITS = "INHERITS"
    DEPENDS_ON = "DEPENDS_ON"
    USES = "USES"
    CONNECTS_TO = "CONNECTS_TO"
    READS = "READS"
    WRITES = "WRITES"
    EXPOSES = "EXPOSES"
    QUERIES = "QUERIES"
    CONSUMES = "CONSUMES"
    PRODUCES = "PRODUCES"
    BELONGS_TO = "BELONGS_TO"
    DEPLOYS_TO = "DEPLOYS_TO"
    REFERENCES = "REFERENCES"
    ROUTES_TO = "ROUTES_TO"
    INTRODUCED_BY = "INTRODUCED_BY"
    MERGED_IN = "MERGED_IN"
    FIXES = "FIXES"
    DISCUSSES = "DISCUSSES"
    DOCUMENTED_IN = "DOCUMENTED_IN"
    RESOLVES = "RESOLVES"
