import {
  CityBuilding,
  CityTrafficHighway,
  StoryModeTourStep,
  MultiplayerCollaborator,
  SubsystemPortal,
} from './metaverse-types';

export const MOCK_CITY_BUILDINGS: CityBuilding[] = [
  {
    id: 'bldg-gw',
    name: 'Kong Ingress Gateway Tower',
    buildingType: 'gateway_tower',
    heightLevel: 95,
    status: 'vibrant_healthy',
    qps: 52000,
    p95LatencyMs: 4.2,
    techDebtHours: 4,
    ownerTeam: 'Edge Infra Team',
    buildingDescription: 'Highest tower in software city handling 52k QPS external traffic.',
    x: 150,
    y: 200,
  },
  {
    id: 'bldg-auth',
    name: 'Auth Router Citadel',
    buildingType: 'microservice_building',
    heightLevel: 75,
    status: 'vibrant_healthy',
    qps: 45000,
    p95LatencyMs: 12.0,
    techDebtHours: 8,
    ownerTeam: 'Identity & Security',
    buildingDescription: 'Stateless JWT RS256 token verification router.',
    x: 400,
    y: 120,
  },
  {
    id: 'bldg-payment',
    name: 'Payment Core Headquarters',
    buildingType: 'microservice_building',
    heightLevel: 88,
    status: 'critical_hotspot',
    qps: 18500,
    p95LatencyMs: 180.0,
    techDebtHours: 42,
    ownerTeam: 'Core Payments Team',
    buildingDescription: 'Payment processing engine experiencing connection pool congestion.',
    x: 400,
    y: 320,
  },
  {
    id: 'bldg-db',
    name: 'PostgreSQL Primary Datacenter',
    buildingType: 'database_datacenter',
    heightLevel: 60,
    status: 'degraded_warning',
    qps: 12000,
    p95LatencyMs: 24.5,
    techDebtHours: 18,
    ownerTeam: 'Database Admins',
    buildingDescription: 'Primary relational data center under 88% CPU load pressure.',
    x: 650,
    y: 280,
  },
  {
    id: 'bldg-kafka',
    name: 'Strimzi Kafka Topic Highway Hub',
    buildingType: 'kafka_highway',
    heightLevel: 70,
    status: 'vibrant_healthy',
    qps: 34000,
    p95LatencyMs: 2.0,
    techDebtHours: 6,
    ownerTeam: 'Event Stream Infra',
    buildingDescription: 'High-speed event bus processing asynchronous checkout events.',
    x: 650,
    y: 450,
  },
];

export const MOCK_CITY_HIGHWAYS: CityTrafficHighway[] = [
  { id: 'hwy-1', sourceBuildingId: 'bldg-gw', targetBuildingId: 'bldg-auth', protocol: 'gRPC', throughputQps: 45000, health: 'healthy' },
  { id: 'hwy-2', sourceBuildingId: 'bldg-gw', targetBuildingId: 'bldg-payment', protocol: 'HTTP/2', throughputQps: 18500, health: 'congested' },
  { id: 'hwy-3', sourceBuildingId: 'bldg-payment', targetBuildingId: 'bldg-db', protocol: 'SQL', throughputQps: 12000, health: 'congested' },
  { id: 'hwy-4', sourceBuildingId: 'bldg-payment', targetBuildingId: 'bldg-kafka', protocol: 'Kafka Stream', throughputQps: 34000, health: 'healthy' },
];

export const MOCK_STORY_STEPS: StoryModeTourStep[] = [
  {
    stepIndex: 1,
    title: 'Welcome to Software City',
    narrationText: 'Welcome. Today we will investigate why Checkout latency spiked to 180ms P95 during peak sales.',
    focusBuildingId: 'bldg-gw',
    actionText: 'Inspect Ingress Gateway Traffic',
    subsystemLink: '/command-center',
  },
  {
    stepIndex: 2,
    title: 'Pinpoint Hotspot Building',
    narrationText: 'Notice the red glowing building: Payment Core Headquarters. P95 latency is 180ms with 42h of technical debt.',
    focusBuildingId: 'bldg-payment',
    actionText: 'Deep Dive Investigation',
    subsystemLink: '/investigate',
  },
  {
    stepIndex: 3,
    title: 'Trace Relational Highway Congestion',
    narrationText: 'The SQL highway between Payment Core and PostgreSQL Datacenter is experiencing 88% CPU lock wait bottlenecks.',
    focusBuildingId: 'bldg-db',
    actionText: 'Simulate Database Migration',
    subsystemLink: '/db-migration',
  },
  {
    stepIndex: 4,
    title: 'AI Remediation Plan',
    narrationText: 'AI CTO recommends deploying Scenario C (Event-Driven Kafka Architecture) to drop P95 latency to 18ms.',
    focusBuildingId: 'bldg-kafka',
    actionText: 'Execute Chaos & Scenario Test',
    subsystemLink: '/scenarios',
  },
];

export const MOCK_MULTIPLAYER_COLLABORATORS: MultiplayerCollaborator[] = [
  { id: 'user-1', name: 'Sarah Chen', role: 'Principal Architect', avatarColor: 'bg-cyan-500', currentFocusBuilding: 'bldg-payment', isVoiceConnected: true },
  { id: 'user-2', name: 'Alex Rivera', role: 'Staff SRE', avatarColor: 'bg-purple-500', currentFocusBuilding: 'bldg-db', isVoiceConnected: true },
  { id: 'user-3', name: 'David Kim', role: 'FinOps Lead', avatarColor: 'bg-emerald-500', currentFocusBuilding: 'bldg-kafka', isVoiceConnected: false },
];

export const MOCK_SUBSYSTEM_PORTALS: SubsystemPortal[] = [
  { id: 'port-1', name: 'AI Mission Control', route: '/command-center', description: 'Central Executive OS', iconName: 'Activity' },
  { id: 'port-2', name: 'AI CTO Workspace', route: '/ai-cto', description: 'Strategic Decision Support', iconName: 'Brain' },
  { id: 'port-3', name: 'Investigation Engine', route: '/investigate', description: 'Deep Root Cause Analysis', iconName: 'Search' },
  { id: 'port-4', name: 'Refactoring Planner', route: '/improve', description: 'Technical Debt Refactoring', iconName: 'Sparkles' },
  { id: 'port-5', name: 'Documentation Engineer', route: '/docs', description: 'Auto Living Docs', iconName: 'BookOpen' },
  { id: 'port-6', name: 'Code Review Intelligence', route: '/review', description: 'Automated PR Signoff', iconName: 'CheckCircle2' },
  { id: 'port-7', name: 'Release Intelligence', route: '/release', description: 'Canary Deployment Risk', iconName: 'Rocket' },
  { id: 'port-8', name: 'Engineering Forecasting', route: '/forecast', description: 'Predictive Velocity', iconName: 'TrendingUp' },
  { id: 'port-9', name: 'Autonomous Workflows', route: '/workflows', description: 'Agentic Workflow Engines', iconName: 'Workflow' },
  { id: 'port-10', name: 'Knowledge Hub', route: '/knowledge', description: 'Engineering Knowledge Graph', iconName: 'Share2' },
  { id: 'port-11', name: 'Repository Explorer', route: '/repositories', description: 'Git Monorepo AST', iconName: 'FolderGit2' },
  { id: 'port-12', name: 'Architecture Intelligence', route: '/architecture', description: 'System Graph Topology', iconName: 'Network' },
  { id: 'port-13', name: 'Simulation Studio', route: '/simulate', description: 'Digital Twin Simulation', iconName: 'Play' },
  { id: 'port-14', name: 'Chaos Studio', route: '/chaos', description: 'Fault Injection Chaos Lab', iconName: 'Flame' },
  { id: 'port-15', name: 'FinOps Cost Simulator', route: '/finops', description: 'Performance & Cloud Spend', iconName: 'DollarSign' },
  { id: 'port-16', name: 'Database Migration Studio', route: '/db-migration', description: 'Zero-Downtime DB Modernization', iconName: 'Database' },
  { id: 'port-17', name: 'Cloud Evolution Studio', route: '/k8s', description: 'Multi-Cloud & GitOps Studio', iconName: 'Server' },
];
