import { DocPage, LiveSyncEvent, DocTypeCategory, DocTypeId } from './doc-types';

export const CATEGORY_DEFINITIONS: { id: DocTypeCategory; label: string; description: string; icon: string }[] = [
  { id: 'overview', label: 'Repository & Architecture', description: 'System overview, top-level topology and architectural intent', icon: 'Globe' },
  { id: 'code_reference', label: 'Code Reference', description: 'Modules, folders, classes, and function-level deep dives', icon: 'Code' },
  { id: 'system_apis', label: 'APIs & Data Layers', description: 'REST APIs, GraphQL schemas, DB models, and schemas', icon: 'Database' },
  { id: 'infrastructure', label: 'Infrastructure & Ops', description: 'K8s, Docker, cloud deployment, and infrastructure topology', icon: 'Server' },
  { id: 'guides', label: 'Developer & Ops Guides', description: 'Onboarding, contribution, testing, security, and troubleshooting', icon: 'BookOpen' },
  { id: 'governance', label: 'Architecture Decisions (ADRs)', description: 'Recorded ADRs, trade-off evaluations, and drift policies', icon: 'FileCheck' },
  { id: 'changelog_handbook', label: 'Changelog & Handbook', description: 'Release notes, migrations, FAQs, glossary, and team handbook', icon: 'History' },
];

export const DOC_TYPES_REGISTRY: { id: DocTypeId; name: string; category: DocTypeCategory; icon: string }[] = [
  { id: 'repository-overview', name: 'Repository Overview', category: 'overview', icon: 'FolderGit2' },
  { id: 'architecture-overview', name: 'Architecture Overview', category: 'overview', icon: 'Network' },
  { id: 'module-doc', name: 'Module Documentation', category: 'code_reference', icon: 'Box' },
  { id: 'folder-doc', name: 'Folder Documentation', category: 'code_reference', icon: 'FolderTree' },
  { id: 'class-doc', name: 'Class Documentation', category: 'code_reference', icon: 'FileCode2' },
  { id: 'function-doc', name: 'Function Documentation', category: 'code_reference', icon: 'Braces' },
  { id: 'api-doc', name: 'API Documentation', category: 'system_apis', icon: 'Webhook' },
  { id: 'database-doc', name: 'Database Documentation', category: 'system_apis', icon: 'Database' },
  { id: 'infrastructure-doc', name: 'Infrastructure Documentation', category: 'infrastructure', icon: 'Server' },
  { id: 'deployment-guide', name: 'Deployment Guide', category: 'infrastructure', icon: 'Rocket' },
  { id: 'developer-guide', name: 'Developer Guide', category: 'guides', icon: 'Terminal' },
  { id: 'getting-started', name: 'Getting Started Guide', category: 'guides', icon: 'Compass' },
  { id: 'contribution-guide', name: 'Contribution Guide', category: 'guides', icon: 'GitPullRequest' },
  { id: 'adr', name: 'Architecture Decisions (ADR)', category: 'governance', icon: 'FileText' },
  { id: 'dependency-guide', name: 'Dependency Guide', category: 'governance', icon: 'Layers' },
  { id: 'testing-guide', name: 'Testing Guide', category: 'guides', icon: 'CheckCircle2' },
  { id: 'security-guide', name: 'Security Guide', category: 'guides', icon: 'ShieldCheck' },
  { id: 'performance-guide', name: 'Performance Guide', category: 'guides', icon: 'Zap' },
  { id: 'troubleshooting-guide', name: 'Troubleshooting Guide', category: 'guides', icon: 'AlertTriangle' },
  { id: 'faq', name: 'Frequently Asked Questions', category: 'changelog_handbook', icon: 'HelpCircle' },
  { id: 'glossary', name: 'Glossary', category: 'changelog_handbook', icon: 'BookMarked' },
  { id: 'release-notes', name: 'Release Notes', category: 'changelog_handbook', icon: 'Tag' },
  { id: 'migration-guides', name: 'Migration Guides', category: 'changelog_handbook', icon: 'ArrowLeftRight' },
  { id: 'changelog', name: 'Changelog', category: 'changelog_handbook', icon: 'Clock' },
  { id: 'engineering-handbook', name: 'Engineering Handbook', category: 'changelog_handbook', icon: 'BookOpen' },
];

export const MOCK_LIVE_EVENTS: LiveSyncEvent[] = [
  {
    id: 'evt-101',
    timestamp: '2 mins ago',
    triggerType: 'api_change',
    source: 'PR #482 merged (PaymentGateway Router update)',
    affectedDocsCount: 3,
    docIds: ['doc-api', 'doc-repo-overview', 'doc-changelog'],
    description: 'Updated API routes and request payload schemas for Payment API & Checkout service.',
    status: 'synced',
  },
  {
    id: 'evt-102',
    timestamp: '14 mins ago',
    triggerType: 'database_change',
    source: 'Alembic Migration 0042_add_tenant_isolation_idx',
    affectedDocsCount: 2,
    docIds: ['doc-database', 'doc-sec-guide'],
    description: 'Added multi-tenant composite indexing and row-level security policy documentation.',
    status: 'synced',
  },
  {
    id: 'evt-103',
    timestamp: '45 mins ago',
    triggerType: 'drift_detected',
    source: 'Architecture Drift Detector (Kafka Consumer loop bypass)',
    affectedDocsCount: 2,
    docIds: ['doc-arch-overview', 'doc-adr'],
    description: 'Flagged unintended direct DB connection inside Payment Worker. Updated ADR trade-off log.',
    status: 'synced',
  },
  {
    id: 'evt-104',
    timestamp: '2 hours ago',
    triggerType: 'simulation_completed',
    source: 'Simulation Studio (100k Peak Traffic Spike)',
    affectedDocsCount: 1,
    docIds: ['doc-perf-guide'],
    description: 'Captured bottleneck in Redis lock contention and auto-generated mitigation checklist.',
    status: 'synced',
  },
];

export const MOCK_DOC_PAGES: DocPage[] = [
  // 1. REPOSITORY OVERVIEW
  {
    id: 'doc-repo-overview',
    typeId: 'repository-overview',
    category: 'overview',
    title: 'CodeAtlas Core OS Repository Overview',
    subtitle: 'System layout, monorepo hierarchy, business capabilities & runtime topology',
    icon: 'FolderGit2',
    slug: 'repository-overview',
    summary: 'CodeAtlas is an AI Operating System for Software Engineering. It combines deep static analysis, vector knowledge graphs, predictive drift detection, and autonomous refactoring pipelines.',
    purpose: 'Provide developers, engineering managers, and security auditors with an instant, continuously updated blueprint of the entire codebase topology and inter-service dependencies.',
    businessContext: 'Enables enterprise engineering teams to reduce developer onboarding time from weeks to minutes, eliminate tech debt drift, and maintain continuous compliance across high-velocity releases.',
    technicalContext: 'Built as a Next.js 16 + React 19 micro-frontend workspace communicating via gRPC/REST with a Python FastAPI backend powered by SQLAlchemy, Alembic, and Neo4j Knowledge Graph.',
    architectureSummary: 'Monorepo structured with `apps/web` for frontend visualization, `apps/backend` for AI engines and FastAPI controllers, and `packages/` for shared schemas and AST parsers.',
    diagrams: [
      {
        id: 'diag-repo-1',
        title: 'High-Level Monorepo Topology',
        type: 'architecture',
        nodes: [
          { id: 'web', label: 'Web Platform (Next.js 16)', type: 'gateway', subtext: 'React 19, Tailwind, xyflow' },
          { id: 'api', label: 'Backend Kernel (FastAPI)', type: 'service', subtext: 'Python 3.12, AsyncIO' },
          { id: 'neo4j', label: 'Knowledge Graph (Neo4j)', type: 'database', subtext: 'AST, Code Graphs, Vector' },
          { id: 'db', label: 'Relational DB (PostgreSQL)', type: 'database', subtext: 'State, Audits, Users' },
          { id: 'sim', label: 'Simulation Studio', type: 'worker', subtext: 'Monte Carlo Stress Test' },
        ],
        edges: [
          { from: 'web', to: 'api', label: 'REST / WS', animated: true },
          { from: 'api', to: 'neo4j', label: 'Cypher Queries', animated: true },
          { from: 'api', to: 'db', label: 'SQLAlchemy', animated: false },
          { from: 'api', to: 'sim', label: 'Async Jobs', animated: true },
        ],
      },
    ],
    dependenciesSummary: 'Node.js 20+, Python 3.12+, PostgreSQL 16, Neo4j 5.x, Redis 7.2.',
    dependenciesList: [
      { name: 'Next.js', version: '16.2.9', type: 'direct', reason: 'Framework for visual dashboard rendering' },
      { name: 'FastAPI', version: '0.110.0', type: 'direct', reason: 'High-performance async Python API backend' },
      { name: 'Neo4j Client', version: '5.18.0', type: 'direct', reason: 'Graph database driver for Knowledge Graph' },
      { name: '@xyflow/react', version: '12.11.1', type: 'direct', reason: 'Interactive node graph visualization' },
    ],
    relatedComponents: [
      { name: 'Backend API Router', path: 'apps/backend/app/main.py', description: 'Core FastAPI router definitions', link: '/repositories' },
      { name: 'Knowledge Intelligence Service', path: 'apps/backend/app/services/knowledge_intelligence.py', description: 'Graph analysis & knowledge extraction engine', link: '/knowledge' },
    ],
    codeExamples: [
      {
        id: 'code-repo-1',
        title: 'Starting Monorepo in Development Mode',
        language: 'bash',
        code: `pnpm install\npnpm run dev --parallel`,
        explanation: 'Launches Next.js on localhost:3000 and Python FastAPI on localhost:8000 concurrently.',
        outputSnippet: `[web]  Ready in 1.2s on http://localhost:3000\n[api]  Uvicorn running on http://127.0.0.1:8000`,
        isExecutable: true,
      },
    ],
    alerts: [
      {
        type: 'important',
        title: 'Environment Prerequisites',
        content: 'Ensure PostgreSQL and Neo4j containers are running via docker-compose up -d before launching apps/backend.',
      },
    ],
    bestPractices: [
      'Always add new API routes under apps/backend/app/api/v1',
      'Ensure typescript strict mode compliance on apps/web changes',
      'Keep database migrations versioned via alembic revision --autogenerate',
    ],
    commonMistakes: [
      'Mutating backend models without updating database schemas',
      'Direct client-side API calls bypassing Next.js server proxies',
    ],
    relatedDocIds: ['doc-arch-overview', 'doc-dev-guide', 'doc-getting-started'],
    aiConfidence: 99.4,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: 'Just now (Live Sync)',
    lastCommitHash: 'a4f9b21',
    lastTrigger: 'file_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'AI Documentation Engineer',
    reviewers: ['@staff-architect', '@lead-dev'],
    interSystemLinks: [
      { system: 'repository_explorer', label: 'Open Repository Explorer', url: '/repositories', description: 'Explore files and directory tree', badge: 'Live AST' },
      { system: 'architecture_graph', label: 'View Architecture Graph', url: '/architecture', description: 'Visualize system topology', badge: 'Interactive' },
      { system: 'knowledge_graph', label: 'Knowledge Graph', url: '/knowledge', description: 'Explore semantic graph nodes', badge: 'Neo4j' },
      { system: 'security', label: 'Security Center', url: '/security', description: 'Scan repository vulnerabilities', badge: 'Passed' },
    ],
    comments: [
      {
        id: 'c-1',
        author: { name: 'Sarah Chen', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150', role: 'Principal Architect' },
        timestamp: '10 mins ago',
        content: 'AI Documentation Engineer automatically updated the monorepo topology diagram after PR #482 merged. Verified!',
        resolved: true,
      },
    ],
    versions: [
      {
        version: 'v2.4',
        updatedAt: '2 mins ago',
        author: 'AI Documentation Engineer',
        commitHash: 'a4f9b21',
        triggerType: 'api_change',
        summaryOfChanges: 'Updated route definitions for Payment API & Checkout service.',
        diffAddedLines: 42,
        diffRemovedLines: 12,
      },
    ],
    presentationSlides: [
      { title: 'CodeAtlas Overview', bulletPoints: ['AI Operating System for Software Engineering', 'Unified Monorepo Architecture', 'Real-time AST & Graph Synchronization'], visualType: 'metrics' },
      { title: 'System Topology', bulletPoints: ['Next.js 16 Web Dashboard', 'Python 3.12 FastAPI Backend', 'Neo4j Graph Database'], visualType: 'diagram' },
    ],
    isBookmarked: true,
    isFavorite: true,
  },

  // 2. ARCHITECTURE OVERVIEW
  {
    id: 'doc-arch-overview',
    typeId: 'architecture-overview',
    category: 'overview',
    title: 'System Architecture & Data Flow Topology',
    subtitle: 'Event-driven message routing, memory engines, and prediction pipelines',
    icon: 'Network',
    slug: 'architecture-overview',
    summary: 'The CodeAtlas architecture is organized around 3 principal tiers: Visual Interface Engine, Autonomous AI Brain Kernel, and Graph/Relational Data Stores.',
    purpose: 'Define boundaries, event schemas, data pipelines, and concurrency controls.',
    businessContext: 'Guarantees sub-second response times for real-time drift detection even on enterprise repositories exceeding 10M lines of code.',
    technicalContext: 'Utilizes asynchronous event streams, distributed Redis locks, and AST vector embeddings in Neo4j.',
    architectureSummary: 'Micro-kernel style backend with independent domain routers (AEO, ASIP, ARE, SPE, EDG).',
    diagrams: [
      {
        id: 'diag-arch-1',
        title: 'Core Event Pipeline Flow',
        type: 'sequence',
        nodes: [
          { id: 'git', label: 'Git Commit Hook', type: 'gateway' },
          { id: 'parser', label: 'Tree-Sitter Parser', type: 'worker' },
          { id: 'graph', label: 'Graph Indexer', type: 'service' },
          { id: 'ai', label: 'AI Documentation Generator', type: 'service' },
        ],
        edges: [
          { from: 'git', to: 'parser', label: 'File Change Event', animated: true },
          { from: 'parser', to: 'graph', label: 'AST Nodes & Symbols', animated: true },
          { from: 'graph', to: 'ai', label: 'Semantic Delta', animated: true },
        ],
      },
    ],
    dependenciesSummary: 'FastAPI background tasks, Celery worker pool, Tree-Sitter AST parser.',
    dependenciesList: [
      { name: 'Tree-Sitter', version: '0.22.2', type: 'direct', reason: 'High speed incremental code AST parsing' },
    ],
    relatedComponents: [
      { name: 'Drift Intelligence Router', path: 'apps/backend/app/api/v1/architecture_drift.py', description: 'Monitors architectural drift', link: '/architecture' },
    ],
    codeExamples: [
      {
        id: 'code-arch-1',
        title: 'Querying Graph Topology',
        language: 'python',
        code: `def fetch_service_topology(repo_id: str):\n    return neo4j_client.query("MATCH (s:Service)-[r:DEPENDS_ON]->(d:Service) RETURN s, r, d")`,
        explanation: 'Retrieves all interconnected service nodes and dependency edges.',
      },
    ],
    alerts: [
      {
        type: 'note',
        title: 'Event Guarantees',
        content: 'Event queues guarantee at-least-once delivery with idempotent graph updates.',
      },
    ],
    bestPractices: ['Decouple IO operations using async tasks'],
    commonMistakes: ['Synchronous HTTP calls between microservices'],
    relatedDocIds: ['doc-repo-overview', 'doc-adr', 'doc-dependency-guide'],
    aiConfidence: 98.9,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '14 mins ago',
    lastCommitHash: '8b10f92',
    lastTrigger: 'architecture_change',
    isStale: false,
    approvalStatus: 'approved',
    author: 'AI Architecture Engine',
    reviewers: ['@cto', '@principal-eng'],
    interSystemLinks: [
      { system: 'architecture_graph', label: 'Architecture Explorer', url: '/architecture', description: 'Live graph of architecture', badge: 'Interactive' },
      { system: 'call_flow', label: 'Call Flow Engine', url: '/analyze', description: 'Trace execution sequences', badge: 'Traces' },
    ],
    comments: [],
    versions: [],
    isBookmarked: true,
  },

  // 3. MODULE DOCUMENTATION
  {
    id: 'doc-module',
    typeId: 'module-doc',
    category: 'code_reference',
    title: 'Knowledge Intelligence Service Module',
    subtitle: 'Extracts, embeds, and categorizes codebase knowledge nodes',
    icon: 'Box',
    slug: 'module-knowledge-intelligence',
    summary: 'The Knowledge Intelligence Module (`apps/backend/app/services/knowledge_intelligence.py`) orchestrates knowledge graph indexing and loss detection.',
    purpose: 'Convert raw code changes into semantic knowledge snapshots.',
    businessContext: 'Prevents institutional knowledge loss when senior engineers rotate or leave.',
    technicalContext: 'Extracts docstrings, commit history metadata, and structural code dependencies.',
    architectureSummary: 'Domain service pattern with transactional graph write buffers.',
    diagrams: [],
    dependenciesSummary: 'SQLAlchemy, Neo4j Driver, OpenAI Embeddings.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-mod-1',
        title: 'Executing Knowledge Loss Audit',
        language: 'python',
        code: `service = KnowledgeIntelligenceService()\nresult = service.analyze_knowledge(db, repo_id="demo")`,
        explanation: 'Triggers knowledge loss calculation across all modified files.',
      },
    ],
    alerts: [],
    bestPractices: ['Use batch transaction writes for large repository re-indexing'],
    commonMistakes: ['N+1 queries when fetching related file nodes'],
    relatedDocIds: ['doc-repo-overview', 'doc-class-doc'],
    aiConfidence: 97.8,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '1 hour ago',
    lastCommitHash: 'f32a10e',
    lastTrigger: 'file_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'AI Documentation Engineer',
    reviewers: [],
    interSystemLinks: [
      { system: 'knowledge_graph', label: 'Knowledge Graph Workspace', url: '/knowledge', description: 'Deep dive into knowledge nodes', badge: 'Graph' },
    ],
    comments: [],
    versions: [],
  },

  // 4. FOLDER DOCUMENTATION
  {
    id: 'doc-folder',
    typeId: 'folder-doc',
    category: 'code_reference',
    title: '`apps/backend/app/api/v1` Folder Structure',
    subtitle: 'FastAPI controller layer and OpenAPI endpoint definitions',
    icon: 'FolderTree',
    slug: 'folder-backend-api-v1',
    summary: 'Contains all REST API v1 endpoints for CodeAtlas backend operations, including AEO, ASIP, AI CTO, and Knowledge graph routes.',
    purpose: 'Maintain structured, versioned REST endpoints.',
    businessContext: 'Serves all client applications and third-party enterprise integrations.',
    technicalContext: 'Each module exports a `router = APIRouter()` included in `main.py`.',
    architectureSummary: 'Clean API routing with modular feature sub-routers.',
    diagrams: [],
    dependenciesSummary: 'FastAPI, Pydantic v2.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [],
    alerts: [],
    bestPractices: ['Keep business logic out of route handlers, delegate to services'],
    commonMistakes: ['Exposing raw SQLAlchemy ORM models directly in endpoints'],
    relatedDocIds: ['doc-api', 'doc-repo-overview'],
    aiConfidence: 99.1,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '3 hours ago',
    lastCommitHash: '9c4b123',
    lastTrigger: 'api_change',
    isStale: false,
    approvalStatus: 'approved',
    author: 'AI Documentation Engineer',
    reviewers: [],
    interSystemLinks: [],
    comments: [],
    versions: [],
  },

  // 5. CLASS DOCUMENTATION
  {
    id: 'doc-class-doc',
    typeId: 'class-doc',
    category: 'code_reference',
    title: '`KnowledgeIntelligenceService` Class Reference',
    subtitle: 'Core class managing graph extraction, metrics calculation, and snapshot history',
    icon: 'FileCode2',
    slug: 'class-knowledge-intelligence-service',
    summary: 'Class encapsulates business rules for detecting knowledge decay, calculating developer contribution density, and indexing memory items.',
    purpose: 'Core domain service class for knowledge lifecycle.',
    businessContext: 'Enables C-level executive knowledge reporting.',
    technicalContext: 'Instantiated per backend process, uses thread-safe database session handles.',
    architectureSummary: 'Singleton service instance with transactional methods.',
    diagrams: [],
    dependenciesSummary: 'SQLAlchemy Session, Neo4j Client.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-class-1',
        title: 'Class Declaration & Signature',
        language: 'python',
        code: `class KnowledgeIntelligenceService:\n    def get_dashboard(self, db: Session, repo_id: str) -> KnowledgeDashboardResponse:\n        ...`,
        explanation: 'Retrieves complete knowledge metrics dashboard for a given repository ID.',
      },
    ],
    alerts: [],
    bestPractices: ['Always handle db transaction rollbacks on exceptions'],
    commonMistakes: ['Leaving db sessions open across thread boundaries'],
    relatedDocIds: ['doc-module', 'doc-function-doc'],
    aiConfidence: 98.4,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '2 hours ago',
    lastCommitHash: '7a12b98',
    lastTrigger: 'file_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'AI Documentation Engineer',
    reviewers: [],
    interSystemLinks: [
      { system: 'repository_explorer', label: 'View File in Explorer', url: '/repositories', description: 'Open source file', badge: 'Source' },
    ],
    comments: [],
    versions: [],
  },

  // 6. FUNCTION DOCUMENTATION
  {
    id: 'doc-function-doc',
    typeId: 'function-doc',
    category: 'code_reference',
    title: '`analyze_knowledge()` Function Reference',
    subtitle: 'Triggers deep repository scanning and re-calculates knowledge loss risk',
    icon: 'Braces',
    slug: 'function-analyze-knowledge',
    summary: 'Asynchronous core function responsible for evaluating file modification recency, developer churn risk, and semantic documentation coverage.',
    purpose: 'Calculate risk scores and trigger auto-update events for stale docs.',
    businessContext: 'Prevents critical code paths from remaining un-documented.',
    technicalContext: 'Iterates through repo files, computes entropy scores, and updates `KnowledgeSnapshot`.',
    architectureSummary: 'Algorithmic scoring function with O(N) complexity over file nodes.',
    diagrams: [],
    dependenciesSummary: 'Python standard library math & AST.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-func-1',
        title: 'Function Signature',
        language: 'python',
        code: `def analyze_knowledge(self, db: Session, repo_id: str) -> KnowledgeDashboardResponse:`,
        explanation: 'Requires active db session and valid repository string identifier.',
      },
    ],
    alerts: [],
    bestPractices: ['Ensure index optimizations are present on file modification tables'],
    commonMistakes: ['Calling function in synchronous request loop for repos > 100k files'],
    relatedDocIds: ['doc-class-doc'],
    aiConfidence: 99.0,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '1 hour ago',
    lastCommitHash: '5e91a02',
    lastTrigger: 'file_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'AI Documentation Engineer',
    reviewers: [],
    interSystemLinks: [],
    comments: [],
    versions: [],
  },

  // 7. API DOCUMENTATION
  {
    id: 'doc-api',
    typeId: 'api-doc',
    category: 'system_apis',
    title: 'CodeAtlas REST & Knowledge API Specification',
    subtitle: 'Complete OpenAPI / Swagger endpoint documentation and payload schemas',
    icon: 'Webhook',
    slug: 'api-documentation',
    summary: 'The CodeAtlas API engine provides endpoints for repository management, graph querying, simulation execution, and AI documentation synchronization.',
    purpose: 'Complete reference for REST endpoints, query parameters, and JSON payloads.',
    businessContext: 'Powers frontend UI and external webhook / CI integrations.',
    technicalContext: 'FastAPI autogenerated schema compliant with OpenAPI 3.1.0 specification.',
    architectureSummary: 'RESTful endpoints with JSON payloads and Bearer JWT authorization.',
    diagrams: [],
    dependenciesSummary: 'FastAPI, Pydantic v2.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-api-1',
        title: 'Fetch Knowledge Dashboard (GET /api/v1/repositories/{repo_id}/knowledge/dashboard)',
        language: 'bash',
        code: `curl -X GET "http://localhost:8000/api/v1/repositories/demo/knowledge/dashboard" \\\n  -H "Authorization: Bearer <your_jwt_token>"`,
        explanation: 'Returns knowledge risk score, recent loss events, and node counts.',
        outputSnippet: `{\n  "risk_score": 12.4,\n  "knowledge_health": "OPTIMAL",\n  "total_nodes": 1420,\n  "stale_docs_count": 0\n}`,
        isExecutable: true,
      },
    ],
    alerts: [
      {
        type: 'tip',
        title: 'Interactive Swagger UI',
        content: 'Access interactive Swagger documentation directly at http://localhost:8000/docs.',
      },
    ],
    bestPractices: ['Always include Bearer Auth header in production calls'],
    commonMistakes: ['Omitting trailing slashes on sub-resource paths'],
    relatedDocIds: ['doc-repo-overview', 'doc-folder'],
    aiConfidence: 99.6,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '2 mins ago',
    lastCommitHash: 'a4f9b21',
    lastTrigger: 'api_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'AI Documentation Engineer',
    reviewers: ['@lead-backend'],
    interSystemLinks: [
      { system: 'call_flow', label: 'Test Route Call Flow', url: '/analyze', description: 'Analyze API latency & call graph', badge: 'Live Trace' },
    ],
    comments: [],
    versions: [],
    isBookmarked: true,
  },

  // 8. DATABASE DOCUMENTATION
  {
    id: 'doc-database',
    typeId: 'database-doc',
    category: 'system_apis',
    title: 'PostgreSQL Relational Schema & Neo4j Graph Models',
    subtitle: 'Data dictionary, entity relationships, indexes, and graph node categories',
    icon: 'Database',
    slug: 'database-documentation',
    summary: 'CodeAtlas uses a hybrid data model: PostgreSQL for transactional state, audits, and user accounts; Neo4j for code AST, dependency graphs, and vector search.',
    purpose: 'Document table schemas, foreign keys, index strategies, and Cypher graph schemas.',
    businessContext: 'Ensures data integrity, multi-tenant isolation, and high query performance.',
    technicalContext: 'SQLAlchemy models in `apps/backend/app/models`, managed via Alembic migrations.',
    architectureSummary: 'Hybrid RDBMS + Graph Database engine with dual write synchronization.',
    diagrams: [
      {
        id: 'diag-db-1',
        title: 'Core Entity Relationship Diagram',
        type: 'dataflow',
        nodes: [
          { id: 'user', label: 'users', type: 'database', subtext: 'id, email, hashed_password' },
          { id: 'repo', label: 'repositories', type: 'database', subtext: 'id, name, git_url, user_id' },
          { id: 'snapshot', label: 'knowledge_snapshots', type: 'database', subtext: 'id, repo_id, risk_score' },
          { id: 'node', label: 'Neo4j :SymbolNode', type: 'database', subtext: 'name, type, file_path' },
        ],
        edges: [
          { from: 'user', to: 'repo', label: '1 : N', animated: false },
          { from: 'repo', to: 'snapshot', label: '1 : N', animated: false },
          { from: 'repo', to: 'node', label: 'Maps to Graph', animated: true },
        ],
      },
    ],
    dependenciesSummary: 'PostgreSQL 16, Neo4j 5.x, Alembic.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-db-1',
        title: 'Cypher Query for Symbol Call Graph',
        language: 'sql',
        code: `MATCH (a:SymbolNode {name: "analyze_knowledge"})-[:CALLS*1..3]->(b:SymbolNode)\nRETURN a.name, b.name, b.file_path`,
        explanation: 'Traverses call dependency tree up to 3 hops deep from target symbol.',
      },
    ],
    alerts: [
      {
        type: 'warning',
        title: 'Schema Migrations',
        content: 'Never modify SQL tables manually; always apply Alembic migration files.',
      },
    ],
    bestPractices: ['Maintain composite indexes on (repo_id, created_at)'],
    commonMistakes: ['Executing un-indexed Cypher graph sweeps without label filters'],
    relatedDocIds: ['doc-sec-guide', 'doc-api'],
    aiConfidence: 98.7,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '14 mins ago',
    lastCommitHash: '0042_tenant',
    lastTrigger: 'database_change',
    isStale: false,
    approvalStatus: 'approved',
    author: 'AI Database Architect',
    reviewers: ['@data-lead'],
    interSystemLinks: [
      { system: 'knowledge_graph', label: 'View Graph Model in Neo4j Workspace', url: '/knowledge', description: 'Explore Neo4j live nodes', badge: 'Neo4j' },
    ],
    comments: [],
    versions: [],
  },

  // 9. INFRASTRUCTURE DOCUMENTATION
  {
    id: 'doc-infra',
    typeId: 'infrastructure-doc',
    category: 'infrastructure',
    title: 'Infrastructure & Kubernetes Cluster Architecture',
    subtitle: 'Containerization, Docker Compose, K8s manifests, Nginx ingress & HPA',
    icon: 'Server',
    slug: 'infrastructure-documentation',
    summary: 'Documents production infrastructure topology, container specifications, Kubernetes deployment manifests, and autoscaling policies.',
    purpose: 'Provide DevOps and Reliability Engineers with infrastructure blueprints.',
    businessContext: 'Ensures 99.99% system availability and automatic elasticity under peak load.',
    technicalContext: 'Docker multi-stage builds (`Dockerfile.backend`, `Dockerfile.frontend`), Kubernetes deployments in `k8s/`.',
    architectureSummary: 'Containerized microservice cluster behind Nginx ingress with TLS termination.',
    diagrams: [],
    dependenciesSummary: 'Docker, Kubernetes 1.28+, Nginx Ingress Controller, Helm.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-infra-1',
        title: 'Spinning up Production Stack via Docker Compose',
        language: 'bash',
        code: `docker-compose -f docker-compose.yml up --build -d`,
        explanation: 'Spins up postgres, neo4j, redis, backend, and frontend containers.',
      },
    ],
    alerts: [],
    bestPractices: ['Use non-root users in production Docker containers'],
    commonMistakes: ['Hardcoding environment secrets in docker-compose.yml'],
    relatedDocIds: ['doc-deploy-guide', 'doc-repo-overview'],
    aiConfidence: 99.2,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '4 hours ago',
    lastCommitHash: '3d81e90',
    lastTrigger: 'config_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'AI DevOps Engineer',
    reviewers: ['@devops-lead'],
    interSystemLinks: [
      { system: 'monitoring', label: 'Infrastructure Health Monitor', url: '/monitor', description: 'Real-time CPU & memory metrics', badge: 'Prometheus' },
    ],
    comments: [],
    versions: [],
  },

  // 10. DEPLOYMENT GUIDE
  {
    id: 'doc-deploy-guide',
    typeId: 'deployment-guide',
    category: 'infrastructure',
    title: 'Production Deployment & Rollout Guide',
    subtitle: 'Step-by-step CI/CD pipeline deployment, zero-downtime migrations & rollback',
    icon: 'Rocket',
    slug: 'deployment-guide',
    summary: 'Comprehensive deployment playbook detailing GitHub Actions CI/CD workflows, canary releases, zero-downtime migrations, and rollback procedures.',
    purpose: 'Guide release engineers through safe, repeatable production deployments.',
    businessContext: 'Eliminates outage risks during deployment windows.',
    technicalContext: 'GitHub Actions trigger Docker image builds, push to ECR/GHCR, and execute `kubectl apply`.',
    architectureSummary: 'Canary rollout strategy with automated rollback on health probe failure.',
    diagrams: [],
    dependenciesSummary: 'GitHub Actions, Helm, Kubernetes.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-deploy-1',
        title: 'Executing Zero-Downtime Alembic Migration',
        language: 'bash',
        code: `kubectl exec -it deployment/codeatlas-backend -- alembic upgrade head`,
        explanation: 'Applies database schema changes before updating backend pods.',
      },
    ],
    alerts: [
      {
        type: 'caution',
        title: 'Database Rollbacks',
        content: 'Destructive column drops must be deployed across two separate release cycles.',
      },
    ],
    bestPractices: ['Always run database migration dry-runs in staging environment'],
    commonMistakes: ['Deploying new code before database migrations complete'],
    relatedDocIds: ['doc-infra', 'doc-database'],
    aiConfidence: 98.8,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '5 hours ago',
    lastCommitHash: '2b19e45',
    lastTrigger: 'config_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'AI Documentation Engineer',
    reviewers: [],
    interSystemLinks: [],
    comments: [],
    versions: [],
  },

  // 11. DEVELOPER GUIDE
  {
    id: 'doc-dev-guide',
    typeId: 'developer-guide',
    category: 'guides',
    title: 'CodeAtlas Developer Engineering Guide',
    subtitle: 'Development standards, local environment configuration & code conventions',
    icon: 'Terminal',
    slug: 'developer-guide',
    summary: 'Standard operating procedures for developing inside the CodeAtlas codebase. Covers code formatting, commit message styles, testing requirements, and PR workflows.',
    purpose: 'Establish consistent engineering standards across team members.',
    businessContext: 'Maintains high code quality and reduces pull request review cycle time.',
    technicalContext: 'Prettier, ESLint, Ruff, pytest, and pnpm monorepo commands.',
    architectureSummary: 'Strict TypeScript & Python type annotations enforced via CI checks.',
    diagrams: [],
    dependenciesSummary: 'pnpm, uv / pip, pre-commit hooks.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-dev-1',
        title: 'Running Code Formatting & Linting',
        language: 'bash',
        code: `pnpm run lint\nruff check apps/backend`,
        explanation: 'Verifies frontend TypeScript and backend Python code style.',
      },
    ],
    alerts: [],
    bestPractices: ['Write unit tests for every new API route or service method'],
    commonMistakes: ['Bypassing pre-commit hooks with git commit --no-verify'],
    relatedDocIds: ['doc-getting-started', 'doc-test-guide'],
    aiConfidence: 99.5,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '6 hours ago',
    lastCommitHash: '1e40a89',
    lastTrigger: 'file_change',
    isStale: false,
    approvalStatus: 'approved',
    author: 'Engineering Director',
    reviewers: [],
    interSystemLinks: [],
    comments: [],
    versions: [],
  },

  // 12. GETTING STARTED GUIDE
  {
    id: 'doc-getting-started',
    typeId: 'getting-started',
    category: 'guides',
    title: 'Getting Started: 5-Minute Developer Quickstart',
    subtitle: 'From zero repository clone to running local AI Operating System',
    icon: 'Compass',
    slug: 'getting-started-guide',
    summary: 'Quickstart guide allowing new team members to set up their local workstation, launch containers, and make their first pull request in under 5 minutes.',
    purpose: 'Accelerate developer onboarding experience.',
    businessContext: 'Drastically cuts down time-to-first-commit for new hires.',
    technicalContext: 'Docker Desktop, Node 20+, Python 3.12, pnpm workspace setup.',
    architectureSummary: 'Local container environment mimicking production Kubernetes topology.',
    diagrams: [],
    dependenciesSummary: 'Docker, Node, Python, pnpm.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-start-1',
        title: 'Clone & Run Quickstart',
        language: 'bash',
        code: `git clone https://github.com/codeatlas/CodeAtlas.git\ncd CodeAtlas\ncp .env.example .env\npnpm install\npnpm run dev`,
        explanation: 'Clones codebase, installs all dependencies, and launches dev servers.',
        outputSnippet: `✔ Dependencies installed (1.4s)\n✔ Next.js server running on http://localhost:3000\n✔ FastAPI kernel running on http://localhost:8000`,
        isExecutable: true,
      },
    ],
    alerts: [
      {
        type: 'tip',
        title: 'Need Demo Data?',
        content: 'Run pnpm run seed:demo to pre-populate local PostgreSQL and Neo4j databases with sample repositories.',
      },
    ],
    bestPractices: ['Copy .env.example to .env and configure local secret keys before launching'],
    commonMistakes: ['Forgetting to launch Docker daemon before running dev script'],
    relatedDocIds: ['doc-repo-overview', 'doc-dev-guide'],
    aiConfidence: 99.8,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '1 day ago',
    lastCommitHash: '9f81a70',
    lastTrigger: 'file_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'AI Documentation Engineer',
    reviewers: ['@community-lead'],
    interSystemLinks: [
      { system: 'repository_explorer', label: 'Explore Repository', url: '/repositories', description: 'Browse codebase tree', badge: 'Interactive' },
    ],
    comments: [],
    versions: [],
    isBookmarked: true,
    isFavorite: true,
  },

  // 13. CONTRIBUTION GUIDE
  {
    id: 'doc-contrib-guide',
    typeId: 'contribution-guide',
    category: 'guides',
    title: 'CodeAtlas Open-Source & Enterprise Contribution Guide',
    subtitle: 'Pull request workflows, branch naming, issue templates & review SLA',
    icon: 'GitPullRequest',
    slug: 'contribution-guide',
    summary: 'Guidelines for submitting bug reports, feature proposals, and pull requests to CodeAtlas.',
    purpose: 'Standardize external and cross-team code contributions.',
    businessContext: 'Ensures community contributions adhere to enterprise security and performance policies.',
    technicalContext: 'GitHub Pull Requests, Conventional Commits format, automated CI checks.',
    architectureSummary: 'Automated CI validation with mandatory 2-peer approval requirement.',
    diagrams: [],
    dependenciesSummary: 'Git, GitHub Actions.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-contrib-1',
        title: 'Branch Naming Format',
        language: 'bash',
        code: `git checkout -b feature/add-vector-search-filter\ngit checkout -b fix/prevent-neo4j-connection-leak`,
        explanation: 'Follow feature/ or fix/ prefix convention.',
      },
    ],
    alerts: [],
    bestPractices: ['Link PRs directly to corresponding GitHub Issue ticket'],
    commonMistakes: ['Submitting jumbo PRs exceeding 500 lines of modified code'],
    relatedDocIds: ['doc-dev-guide', 'doc-getting-started'],
    aiConfidence: 99.1,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '2 days ago',
    lastCommitHash: '4e12a90',
    lastTrigger: 'file_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'Open Source Maintainer',
    reviewers: [],
    interSystemLinks: [],
    comments: [],
    versions: [],
  },

  // 14. ARCHITECTURE DECISION RECORDS (ADR)
  {
    id: 'doc-adr',
    typeId: 'adr',
    category: 'governance',
    title: 'ADR-0042: Hybrid Graph-Relational Architecture for AI OS',
    subtitle: 'Decision record for pairing PostgreSQL transactional DB with Neo4j AST Graph',
    icon: 'FileText',
    slug: 'adr-0042-hybrid-graph-relational',
    summary: 'ADR documenting the technical decision, trade-offs, and consequences of adopting Neo4j as a secondary graph store alongside PostgreSQL.',
    purpose: 'Record architectural intent and rationale for future engineering teams.',
    businessContext: 'Enables sub-second query performance for multi-hop code dependency traversals.',
    technicalContext: 'Evaluated PostgreSQL pgvector vs. Native Neo4j Cypher graph engine. Chose Neo4j for native multi-hop graph path queries.',
    architectureSummary: 'Dual-store topology with eventual consistency via Redis event queues.',
    diagrams: [],
    dependenciesSummary: 'Neo4j, PostgreSQL.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-adr-1',
        title: 'ADR Metadata Schema',
        language: 'json',
        code: `{\n  "adr_number": 42,\n  "status": "APPROVED",\n  "date": "2026-06-15",\n  "decision": "Adopt Neo4j 5.x alongside PostgreSQL 16"\n}`,
        explanation: 'Structured metadata recorded in CodeAtlas ADR registry.',
      },
    ],
    alerts: [
      {
        type: 'important',
        title: 'Decision Status',
        content: 'Status: APPROVED. Re-evaluation scheduled if graph size exceeds 500M nodes.',
      },
    ],
    bestPractices: ['Document all rejected alternatives with specific benchmark metrics'],
    commonMistakes: ['Bypassing ADR creation when introducing major database technologies'],
    relatedDocIds: ['doc-arch-overview', 'doc-database'],
    aiConfidence: 99.7,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '45 mins ago',
    lastCommitHash: 'adr-0042',
    lastTrigger: 'drift_detected',
    isStale: false,
    approvalStatus: 'approved',
    author: 'Chief Architect',
    reviewers: ['@architecture-council'],
    interSystemLinks: [
      { system: 'architecture_graph', label: 'Open ADR Intelligence Studio', url: '/architecture', description: 'View ADR graph impact', badge: 'ADR Studio' },
    ],
    comments: [],
    versions: [],
    isBookmarked: true,
  },

  // 15. DEPENDENCY GUIDE
  {
    id: 'doc-dep-guide',
    typeId: 'dependency-guide',
    category: 'governance',
    title: 'Dependency Management & Vulnerability Auditing',
    subtitle: 'Package policies, breaking change reviews & license compliance',
    icon: 'Layers',
    slug: 'dependency-guide',
    summary: 'Guidelines for introducing third-party packages, managing version locks, and resolving security vulnerabilities detected by Dependabot and Snyk.',
    purpose: 'Enforce enterprise security and license compliance across all workspace packages.',
    businessContext: 'Protects CodeAtlas from supply chain attacks and copyleft license risks.',
    technicalContext: 'pnpm package overrides, Python requirements locking via pip-tools.',
    architectureSummary: 'Automated CI security gate checking package checksums.',
    diagrams: [],
    dependenciesSummary: 'pnpm, Dependabot, Renovate.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [],
    alerts: [],
    bestPractices: ['Prefer zero-dependency libraries whenever possible'],
    commonMistakes: ['Adding duplicate utility packages already available in workspace'],
    relatedDocIds: ['doc-sec-guide', 'doc-repo-overview'],
    aiConfidence: 98.5,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '1 day ago',
    lastCommitHash: 'dep-policy-v2',
    lastTrigger: 'dependency_change',
    isStale: false,
    approvalStatus: 'approved',
    author: 'AI Security Auditor',
    reviewers: [],
    interSystemLinks: [
      { system: 'dependency_graph', label: 'Dependency Graph Explorer', url: '/dependency-graph', description: 'Visualize package dependencies', badge: 'Graph' },
    ],
    comments: [],
    versions: [],
  },

  // 16. TESTING GUIDE
  {
    id: 'doc-test-guide',
    typeId: 'testing-guide',
    category: 'guides',
    title: 'Automated Testing & Quality Assurance Suite',
    subtitle: 'Unit testing with pytest, frontend testing with Playwright, and DeepEval AI benchmarks',
    icon: 'CheckCircle2',
    slug: 'testing-guide',
    summary: 'Comprehensive testing strategy covering unit tests, integration tests, end-to-end browser tests, and AI evaluation benchmarks.',
    purpose: 'Maintain >85% code coverage and zero regression releases.',
    businessContext: 'Guarantees reliable behavior across complex AI reasoning pipelines.',
    technicalContext: 'pytest, Playwright, DeepEval, Jest/Vitest.',
    architectureSummary: 'Multi-tiered test execution in GitHub Actions CI.',
    diagrams: [],
    dependenciesSummary: 'pytest, playwright, deepeval.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-test-1',
        title: 'Running Backend Test Suite',
        language: 'bash',
        code: `pytest apps/backend/tests -v --cov=app`,
        explanation: 'Executes all Python backend tests and generates coverage report.',
        outputSnippet: `================ 42 passed in 3.12s ================\nCoverage: 88.4%`,
        isExecutable: true,
      },
    ],
    alerts: [],
    bestPractices: ['Mock external LLM API responses in unit test suites'],
    commonMistakes: ['Writing flaky E2E tests dependent on un-seeded database state'],
    relatedDocIds: ['doc-dev-guide', 'doc-perf-guide'],
    aiConfidence: 99.3,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '1 day ago',
    lastCommitHash: '5a32901',
    lastTrigger: 'file_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'QA Lead',
    reviewers: [],
    interSystemLinks: [],
    comments: [],
    versions: [],
  },

  // 17. SECURITY GUIDE
  {
    id: 'doc-sec-guide',
    typeId: 'security-guide',
    category: 'guides',
    title: 'Enterprise Security, Auth & Vulnerability Policies',
    subtitle: 'JWT token handling, multi-tenant RBAC, SQL injection prevention & secrets management',
    icon: 'ShieldCheck',
    slug: 'security-guide',
    summary: 'Security hardening guide detailing authorization protocols, row-level database security policies, secret rotation, and threat models.',
    purpose: 'Ensure SOC2 and ISO27001 compliance for enterprise deployments.',
    businessContext: 'Protects proprietary client codebase data and API access tokens.',
    technicalContext: 'FastAPI HTTPBearer authentication middleware, bcrypt password hashing, AES-256 secret encryption.',
    architectureSummary: 'Zero-trust API model with token validation on every endpoint.',
    diagrams: [],
    dependenciesSummary: 'PyJWT, passlib, cryptography.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-sec-1',
        title: 'JWT Authentication Middleware Pattern',
        language: 'python',
        code: `def get_current_user(token: str = Depends(oauth2_scheme)) -> User:\n    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[ALGORITHM])\n    return user`,
        explanation: 'Validates token and injects current user instance into endpoint.',
      },
    ],
    alerts: [
      {
        type: 'caution',
        title: 'Secret Leak Prevention',
        content: 'Gitleaks is enforced on pre-commit hooks. Never commit API keys or private certificates.',
      },
    ],
    bestPractices: ['Rotate SECRET_KEY every 90 days in production'],
    commonMistakes: ['Logging un-masked authorization headers in debug logs'],
    relatedDocIds: ['doc-database', 'doc-api'],
    aiConfidence: 99.7,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '14 mins ago',
    lastCommitHash: 'sec-audit-42',
    lastTrigger: 'security_alert',
    isStale: false,
    approvalStatus: 'approved',
    author: 'Chief Information Security Officer',
    reviewers: ['@security-team'],
    interSystemLinks: [
      { system: 'security', label: 'Open Security Center', url: '/security', description: 'Real-time security vulnerability dashboard', badge: 'SOC2' },
    ],
    comments: [],
    versions: [],
    isBookmarked: true,
  },

  // 18. PERFORMANCE GUIDE
  {
    id: 'doc-perf-guide',
    typeId: 'performance-guide',
    category: 'guides',
    title: 'Performance Optimization & Benchmarking Playbook',
    subtitle: 'Redis caching strategies, database query tuning & frontend 60 FPS rendering',
    icon: 'Zap',
    slug: 'performance-guide',
    summary: 'Playbook for profiling, optimizing, and maintaining peak system responsiveness across large enterprise repositories.',
    purpose: 'Guide engineers in debugging high latencies or memory spikes.',
    businessContext: 'Ensures sub-second user experience for engineering teams worldwide.',
    technicalContext: 'Redis 7.2 response caching, React Virtualization for large lists, Web Workers for heavy client graph calculations.',
    architectureSummary: 'Multi-layer caching strategy: HTTP CDN -> Redis Cache -> In-Memory L1.',
    diagrams: [],
    dependenciesSummary: 'Redis, py-spy, Chrome DevTools.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-perf-1',
        title: 'Redis Caching Decorator Pattern',
        language: 'python',
        code: `@cache_response(ttl_seconds=300)\ndef get_repo_metrics(repo_id: str):\n    return compute_heavy_analytics(repo_id)`,
        explanation: 'Caches analytical calculation results in Redis for 5 minutes.',
      },
    ],
    alerts: [],
    bestPractices: ['Use select_related and joinedload in SQLAlchemy to avoid N+1 queries'],
    commonMistakes: ['Re-rendering large SVG graphs on every state toggle'],
    relatedDocIds: ['doc-arch-overview', 'doc-database'],
    aiConfidence: 99.0,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '2 hours ago',
    lastCommitHash: 'perf-opt-102',
    lastTrigger: 'performance_optimization',
    isStale: false,
    approvalStatus: 'live',
    author: 'AI Performance Specialist',
    reviewers: [],
    interSystemLinks: [
      { system: 'performance', label: 'Performance & Health Center', url: '/health', description: 'Live performance metrics & latency graphs', badge: 'Metrics' },
      { system: 'simulation', label: 'Simulation Studio', url: '/simulate', description: 'Run traffic stress simulations', badge: 'Monte Carlo' },
    ],
    comments: [],
    versions: [],
  },

  // 19. TROUBLESHOOTING GUIDE
  {
    id: 'doc-troubleshoot-guide',
    typeId: 'troubleshooting-guide',
    category: 'guides',
    title: 'Troubleshooting & Incident Resolution Manual',
    subtitle: 'Diagnosing container crashes, Neo4j timeouts, database locks & memory leaks',
    icon: 'AlertTriangle',
    slug: 'troubleshooting-guide',
    summary: 'Operational runbook for diagnosing and resolving common system errors, infrastructure failures, and connectivity issues.',
    purpose: 'Provide fast resolution steps during live incidents.',
    businessContext: 'Minimizes Mean Time To Resolution (MTTR) during system outages.',
    technicalContext: 'Kubernetes logs, FastAPI stack traces, Neo4j connection pool diagnostics.',
    architectureSummary: 'Centralized log aggregation with automated alert triggers.',
    diagrams: [],
    dependenciesSummary: 'kubectl, docker logs, tail.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-trouble-1',
        title: 'Resetting Stuck Neo4j Graph Connection Pool',
        language: 'bash',
        code: `kubectl exec -it deployment/codeatlas-backend -- python -c "from app.core.neo4j_client import neo4j_client; neo4j_client.reconnect()"`,
        explanation: 'Forces immediate connection pool re-initialization.',
      },
    ],
    alerts: [
      {
        type: 'warning',
        title: 'High CPU Alerts',
        content: 'If backend pod CPU exceeds 90%, check for unbounded Cypher recursive queries in Neo4j logs.',
      },
    ],
    bestPractices: ['Check Prometheus Grafana dashboard before restarting containers'],
    commonMistakes: ['Killing database pods without checking pending transaction locks'],
    relatedDocIds: ['doc-infra', 'doc-deploy-guide'],
    aiConfidence: 98.9,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '1 day ago',
    lastCommitHash: 'runbook-v3',
    lastTrigger: 'file_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'Site Reliability Director',
    reviewers: [],
    interSystemLinks: [
      { system: 'ai_investigation', label: 'AI Investigation Engine', url: '/investigate', description: 'Run automated root cause analysis', badge: 'AI Root Cause' },
    ],
    comments: [],
    versions: [],
  },

  // 20. FAQ
  {
    id: 'doc-faq',
    typeId: 'faq',
    category: 'changelog_handbook',
    title: 'Frequently Asked Questions (FAQ)',
    subtitle: 'Answers to common developer, architect, and administrative queries',
    icon: 'HelpCircle',
    slug: 'frequently-asked-questions',
    summary: 'Curated list of answers to recurring questions about CodeAtlas setup, AI accuracy, graph synchronization, and security data handling.',
    purpose: 'Self-service answers for common team questions.',
    businessContext: 'Reduces internal support tickets and slack interruptions.',
    technicalContext: 'Aggregated from team Q&A channels and developer feedback.',
    architectureSummary: 'Knowledge base updated automatically by AI Documentation Engineer.',
    diagrams: [],
    dependenciesSummary: '',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [],
    alerts: [],
    bestPractices: ['Check FAQ before opening a internal architecture ticket'],
    commonMistakes: ['Assuming local dev changes sync without running git commit'],
    relatedDocIds: ['doc-getting-started', 'doc-dev-guide'],
    aiConfidence: 99.4,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '3 days ago',
    lastCommitHash: 'faq-sync',
    lastTrigger: 'file_change',
    isStale: false,
    approvalStatus: 'approved',
    author: 'AI Documentation Engineer',
    reviewers: [],
    interSystemLinks: [],
    comments: [],
    versions: [],
  },

  // 21. GLOSSARY
  {
    id: 'doc-glossary',
    typeId: 'glossary',
    category: 'changelog_handbook',
    title: 'Engineering Taxonomy & System Glossary',
    subtitle: 'Standardized terminology, domain definitions & acronym reference',
    icon: 'BookMarked',
    slug: 'glossary',
    summary: 'Comprehensive dictionary of domain terms, architectural acronyms (AEO, ASIP, ARE, SPE, EDG), and core CodeAtlas concepts.',
    purpose: 'Standardize language across engineering, product, and executive teams.',
    businessContext: 'Prevents miscommunication during cross-functional planning.',
    technicalContext: 'Vector lookup dictionary used in AI query synthesis.',
    architectureSummary: 'Canonical ontology for CodeAtlas knowledge graph.',
    diagrams: [],
    dependenciesSummary: '',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [],
    alerts: [],
    bestPractices: ['Reference glossary terms when naming new microservices or classes'],
    commonMistakes: ['Creating duplicate acronyms for different sub-systems'],
    relatedDocIds: ['doc-repo-overview', 'doc-handbook'],
    aiConfidence: 99.9,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '4 days ago',
    lastCommitHash: 'glossary-v1',
    lastTrigger: 'file_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'Principal Knowledge Engineer',
    reviewers: [],
    interSystemLinks: [],
    comments: [],
    versions: [],
  },

  // 22. RELEASE NOTES
  {
    id: 'doc-release-notes',
    typeId: 'release-notes',
    category: 'changelog_handbook',
    title: 'CodeAtlas v4.8 Release Notes & Feature Highlights',
    subtitle: 'AI Documentation Engineer, real-time live sync & inter-system deep linking',
    icon: 'Tag',
    slug: 'release-notes-v4-8',
    summary: 'Official release notes for CodeAtlas v4.8. Highlights the launch of the AI Documentation Engineer, continuous live auto-sync, and deep interconnectivity.',
    purpose: 'Inform engineering teams and stakeholders of new platform capabilities.',
    businessContext: 'Drives platform adoption and highlights productivity gains.',
    technicalContext: 'Synthesized directly from git commit history and closed pull requests.',
    architectureSummary: 'Major platform upgrade adding autonomous doc synthesis engine.',
    diagrams: [],
    dependenciesSummary: 'Next.js 16, React 19, FastAPI 0.110.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [],
    alerts: [
      {
        type: 'tip',
        title: 'New Feature Available',
        content: 'Try pressing Cmd+K inside the Documentation Workspace to perform instant AI semantic searches!',
      },
    ],
    bestPractices: ['Review release notes after every minor version upgrade'],
    commonMistakes: ['Upgrading backend without reviewing database migration notes'],
    relatedDocIds: ['doc-changelog', 'doc-migration-guide'],
    aiConfidence: 99.8,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '1 hour ago',
    lastCommitHash: 'v4.8.0-rel',
    lastTrigger: 'api_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'Product Management & AI Team',
    reviewers: [],
    interSystemLinks: [],
    comments: [],
    versions: [],
  },

  // 23. MIGRATION GUIDES
  {
    id: 'doc-migration-guide',
    typeId: 'migration-guides',
    category: 'changelog_handbook',
    title: 'v4.0 -> v4.8 API & Database Migration Guide',
    subtitle: 'Upgrading database schemas, API routes, and configuration environment variables',
    icon: 'ArrowLeftRight',
    slug: 'migration-guide-v4-8',
    summary: 'Step-by-step upgrade guide for migrating self-hosted CodeAtlas enterprise deployments from v4.0 to v4.8 without data loss.',
    purpose: 'Provide safe migration paths for infrastructure teams.',
    businessContext: 'Ensures seamless enterprise platform upgrades.',
    technicalContext: 'Alembic migration sequence `0038_to_0042`, Neo4j constraint updates.',
    architectureSummary: 'Backward-compatible DB migration scripts.',
    diagrams: [],
    dependenciesSummary: 'Alembic 1.13+, Neo4j Migrations.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [
      {
        id: 'code-mig-1',
        title: 'Executing Sequential Database Upgrade',
        language: 'bash',
        code: `alembic upgrade +4`,
        explanation: 'Applies database revisions 0039 through 0042 sequentially.',
      },
    ],
    alerts: [],
    bestPractices: ['Take a full PostgreSQL pg_dump snapshot before initiating upgrade'],
    commonMistakes: ['Skipping intermediate Alembic migration steps'],
    relatedDocIds: ['doc-release-notes', 'doc-database'],
    aiConfidence: 99.2,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '1 day ago',
    lastCommitHash: 'mig-v4.8',
    lastTrigger: 'database_change',
    isStale: false,
    approvalStatus: 'approved',
    author: 'Lead Infrastructure Engineer',
    reviewers: [],
    interSystemLinks: [],
    comments: [],
    versions: [],
  },

  // 24. CHANGELOG
  {
    id: 'doc-changelog',
    typeId: 'changelog',
    category: 'changelog_handbook',
    title: 'Repository Change History & Commit Audit Log',
    subtitle: 'Automated live commit stream and PR change history breakdown',
    icon: 'Clock',
    slug: 'repository-changelog',
    summary: 'Real-time updated changelog tracking all merged pull requests, commit hashes, author attributions, and architectural impacts.',
    purpose: 'Provide continuous audit trail of code modifications.',
    businessContext: 'Satisfies compliance audit requirements for financial and healthcare software.',
    technicalContext: 'Generated via Git log analysis and GitHub Webhook ingestion.',
    architectureSummary: 'Event stream recording git commit deltas in real-time.',
    diagrams: [],
    dependenciesSummary: 'Git CLI, GitHub Webhooks.',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [],
    alerts: [],
    bestPractices: ['Use conventional commit messages (feat:, fix:, chore:, refactor:)'],
    commonMistakes: ['Squashing commits without preserving original PR issue references'],
    relatedDocIds: ['doc-release-notes', 'doc-repo-overview'],
    aiConfidence: 100.0,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '2 mins ago',
    lastCommitHash: 'a4f9b21',
    lastTrigger: 'file_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'AI Documentation Engineer',
    reviewers: [],
    interSystemLinks: [],
    comments: [],
    versions: [],
  },

  // 25. ENGINEERING HANDBOOK
  {
    id: 'doc-handbook',
    typeId: 'engineering-handbook',
    category: 'changelog_handbook',
    title: 'CodeAtlas Engineering Organization Handbook',
    subtitle: 'Values, team structure, incident response protocols, and career ladders',
    icon: 'BookOpen',
    slug: 'engineering-handbook',
    summary: 'The central culture and operational handbook for CodeAtlas engineering teams. Outlines engineering principles, review SLAs, on-call schedules, and career growth paths.',
    purpose: 'Guide team culture, productivity standards, and engineering operations.',
    businessContext: 'Fosters high-trust, autonomous, high-velocity engineering culture.',
    technicalContext: 'Living document maintained by engineering leadership and updated continuously.',
    architectureSummary: 'Organizational operating manual for enterprise engineering teams.',
    diagrams: [],
    dependenciesSummary: '',
    dependenciesList: [],
    relatedComponents: [],
    codeExamples: [],
    alerts: [
      {
        type: 'note',
        title: 'Core Principle',
        content: 'Engineering Core Principle #1: Autonomous automation over repetitive manual effort.',
      },
    ],
    bestPractices: ['Review handbook when taking on team lead or on-call duties'],
    commonMistakes: ['Resolving incidents without filing an post-mortem incident report'],
    relatedDocIds: ['doc-dev-guide', 'doc-glossary'],
    aiConfidence: 99.6,
    confidenceModel: 'CodeAtlas-Synthesizer-v4',
    lastUpdated: '1 week ago',
    lastCommitHash: 'handbook-2026',
    lastTrigger: 'file_change',
    isStale: false,
    approvalStatus: 'live',
    author: 'VP of Engineering',
    reviewers: ['@eng-council'],
    interSystemLinks: [],
    comments: [],
    versions: [],
    isBookmarked: true,
  },
];
