import {
  WorkflowTemplate,
  ExecutionNode,
  AIAgentState,
  AutonomousTaskItem,
  WorkflowHistoryRecord,
  InterSystemLink,
} from './workflow-types';

export const MOCK_WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'wf-incident',
    name: 'Investigate Production Incident',
    category: 'incident',
    purpose: 'Root cause analysis, telemetry correlation, failure chain simulation, and postmortem generation.',
    requiredInputs: ['Incident Severity', 'Affected Service Name', 'Prometheus Alert Log'],
    expectedOutputs: ['Root Cause Diagnosis', 'Failure Chain Graph', 'Automated Postmortem Draft', 'PR Patch'],
    estimatedDuration: '12 mins',
    requiredPermissions: ['Telemetry Read', 'Code Review Approve'],
    aiConfidencePct: 98.4,
    tags: ['SEV-1', 'Telemetry', 'SRE'],
    assignedAgents: ['security_agent', 'performance_agent', 'simulation_agent', 'code_review_agent'],
  },
  {
    id: 'wf-repo-analyze',
    name: 'Analyze New Repository & Onboarding',
    category: 'onboarding',
    purpose: 'Tree-Sitter AST parsing, architectural topology mapping, dependency graph build, and living docs generation.',
    requiredInputs: ['Git Repository URL', 'Default Branch'],
    expectedOutputs: ['Architecture Topology Map', 'Knowledge Graph Nodes', 'Living README', 'ADR Index'],
    estimatedDuration: '8 mins',
    requiredPermissions: ['Repo Read', 'Graph Write'],
    aiConfidencePct: 99.2,
    tags: ['AST', 'Graph', 'Onboarding'],
    assignedAgents: ['repository_agent', 'architecture_agent', 'documentation_agent', 'knowledge_graph_agent'],
  },
  {
    id: 'wf-arch-review',
    name: 'Architecture Review & Drift Detection',
    category: 'architecture',
    purpose: 'Audit domain layer boundaries, detect circular dependencies, evaluate ADR compliance, and flag layer bypasses.',
    requiredInputs: ['Target Microservice Component', 'ADR Compliance Policy'],
    expectedOutputs: ['Drift Matrix', 'Circular Dependency Warning', 'Refactoring Proposal'],
    estimatedDuration: '15 mins',
    requiredPermissions: ['Architecture Write'],
    aiConfidencePct: 96.8,
    tags: ['Hexagonal', 'ADR', 'Drift'],
    assignedAgents: ['architecture_agent', 'refactoring_agent' as any, 'forecast_agent'],
  },
  {
    id: 'wf-security-audit',
    name: 'Security Audit & Vulnerability Remediation',
    category: 'security',
    purpose: 'OWASP Top 10 SAST audit, dependency CVE scan, license compliance check, and automated patch PR generation.',
    requiredInputs: ['Target Repo', 'Package Lock File'],
    expectedOutputs: ['OWASP Audit Scorecard', 'CVE Upgrade Plan', 'Automated Security PR'],
    estimatedDuration: '10 mins',
    requiredPermissions: ['Security Audit', 'PR Create'],
    aiConfidencePct: 99.0,
    tags: ['OWASP', 'CVE', 'Security'],
    assignedAgents: ['security_agent', 'code_review_agent'],
  },
  {
    id: 'wf-perf-opt',
    name: 'Performance Optimization & Latency Drop',
    category: 'performance',
    purpose: 'Monte Carlo traffic load simulation, Redis cache pressure audit, un-indexed query detection, and latency optimization.',
    requiredInputs: ['Target Endpoint', 'Peak Traffic Target QPS'],
    expectedOutputs: ['P95 Latency Forecast', 'Database Index DDL', 'Caching Strategy Plan'],
    estimatedDuration: '14 mins',
    requiredPermissions: ['Simulation Run'],
    aiConfidencePct: 95.5,
    tags: ['Monte Carlo', 'P95', 'Redis'],
    assignedAgents: ['performance_agent', 'simulation_agent'],
  },
  {
    id: 'wf-tech-debt',
    name: 'Technical Debt Cleanup & Refactoring',
    category: 'debt',
    purpose: 'Cyclomatic complexity reduction, monolithic method extraction, test coverage generation, and debt hours reduction.',
    requiredInputs: ['Repository Path', 'Complexity Threshold'],
    expectedOutputs: ['Refactoring Diff', 'Unit Test Suite (90%+)', 'Debt Reduction Summary'],
    estimatedDuration: '18 mins',
    requiredPermissions: ['Code Write', 'PR Create'],
    aiConfidencePct: 94.2,
    tags: ['Refactor', 'Complexity', 'Pytest'],
    assignedAgents: ['code_review_agent', 'documentation_agent'],
  },
  {
    id: 'wf-release-prep',
    name: 'Prepare Release Candidate & Signoff',
    category: 'release',
    purpose: '10-stage release pipeline signoff, pre-deployment risk scorecard evaluation, rollback MTTR estimation, and canary deployment.',
    requiredInputs: ['Release Version Candidate', 'Git Commit Hash'],
    expectedOutputs: ['Release Scorecard (96/100)', 'Rollback Execution Script', 'Istio Route Config'],
    estimatedDuration: '10 mins',
    requiredPermissions: ['Release Signoff', 'Deploy Gate'],
    aiConfidencePct: 99.6,
    tags: ['Canary', 'Istio', 'Rollback'],
    assignedAgents: ['release_agent', 'forecast_agent', 'security_agent'],
  },
];

export const MOCK_EXECUTION_NODES: ExecutionNode[] = [
  {
    id: 'node-1',
    stepNumber: 1,
    label: 'Repository Connected & Commit Ingested',
    agentRole: 'repository_agent',
    status: 'COMPLETED',
    duration: '42s',
    aiExplanation: 'Tree-Sitter parsed 1,420 AST symbols across PaymentService and AuthRouter.',
    evidenceArtifacts: ['AST Symbol Index v4.8.0', 'Git Commit Delta Ingested'],
  },
  {
    id: 'node-2',
    stepNumber: 2,
    label: 'Architecture Topology Map Generated',
    agentRole: 'architecture_agent',
    status: 'COMPLETED',
    duration: '1m 15s',
    aiExplanation: 'Evaluated ADR-0042 hybrid graph-relational trade-offs. 0 layer bypasses detected.',
    evidenceArtifacts: ['Hexagonal Boundary Graph', 'ADR-0042 Compliance Verified'],
  },
  {
    id: 'node-3',
    stepNumber: 3,
    label: 'Dependency Graph Built & Knowledge Graph Updated',
    agentRole: 'knowledge_graph_agent',
    status: 'COMPLETED',
    duration: '55s',
    aiExplanation: 'Neo4j Cypher graph updated with 342 inter-service dependency edges.',
    evidenceArtifacts: ['Neo4j Cypher Update Log', 'Dependency Vulnerability Scan'],
  },
  {
    id: 'node-4',
    stepNumber: 4,
    label: 'AI Investigation & OWASP Security Audit',
    agentRole: 'security_agent',
    status: 'COMPLETED',
    duration: '2m 10s',
    aiExplanation: '1 Critical SQL injection finding resolved with parameterized SQLAlchemy update statement.',
    evidenceArtifacts: ['OWASP Top 10 Audit Report', 'SQL Injection Refactor Patch'],
  },
  {
    id: 'node-5',
    stepNumber: 5,
    label: 'Monte Carlo Stress Test Simulation',
    agentRole: 'simulation_agent',
    status: 'COMPLETED',
    duration: '1m 30s',
    aiExplanation: 'Simulated 100k peak user traffic spike. Latency dropped from 340ms to 24.2ms.',
    evidenceArtifacts: ['100k QPS Load Graph', 'Redis Memory Profile'],
  },
  {
    id: 'node-6',
    stepNumber: 6,
    label: 'Living Documentation & ADR Updated',
    agentRole: 'documentation_agent',
    status: 'COMPLETED',
    duration: '45s',
    aiExplanation: 'Living documentation synchronized across 25 document types with zero staleness.',
    evidenceArtifacts: ['ADR-0043 Drafted', 'API Spec Living Sync'],
  },
  {
    id: 'node-7',
    stepNumber: 7,
    label: 'Automated Recommendations & PR Generation',
    agentRole: 'code_review_agent',
    status: 'AWAITING_APPROVAL',
    duration: 'Live',
    aiExplanation: 'PR #482 generated with 342 additions and 118 deletions awaiting human signoff.',
    evidenceArtifacts: ['PR #482 Draft', 'Rollback MTTR 1.8 mins'],
    requiresApproval: true,
  },
];

export const MOCK_AI_AGENTS: AIAgentState[] = [
  {
    role: 'architecture_agent',
    displayName: 'Architecture Agent',
    avatar: '🏛️',
    currentTask: 'Verifying Hexagonal Domain Isolation',
    status: 'COMPLETED',
    progressPct: 100,
    activeArtifact: 'ADR-0042 Verified',
  },
  {
    role: 'repository_agent',
    displayName: 'Repository Analysis Agent',
    avatar: '📂',
    currentTask: 'AST Symbol Ingestion',
    status: 'COMPLETED',
    progressPct: 100,
    activeArtifact: '1,420 Symbols Parsed',
  },
  {
    role: 'security_agent',
    displayName: 'Security Agent',
    avatar: '🛡️',
    currentTask: 'OWASP SAST Audit & CVE Remediation',
    status: 'COMPLETED',
    progressPct: 100,
    activeArtifact: 'PyYAML CVE Remediation PR',
  },
  {
    role: 'performance_agent',
    displayName: 'Performance Agent',
    avatar: '⚡',
    currentTask: 'Redis Cache Eviction Rate Audit',
    status: 'COMPLETED',
    progressPct: 100,
    activeArtifact: 'P95 Latency 24.2ms',
  },
  {
    role: 'simulation_agent',
    displayName: 'Simulation Agent',
    avatar: '🎲',
    currentTask: '100k Peak QPS Traffic Load Test',
    status: 'COMPLETED',
    progressPct: 100,
    activeArtifact: 'Monte Carlo Stress Test Graph',
  },
  {
    role: 'code_review_agent',
    displayName: 'Code Review Agent',
    avatar: '🔍',
    currentTask: 'Awaiting Human Approval on PR #482',
    status: 'AWAITING_HUMAN',
    progressPct: 92,
    activeArtifact: 'PR #482 Ready for Approval',
  },
  {
    role: 'documentation_agent',
    displayName: 'Documentation Agent',
    avatar: '📝',
    currentTask: 'Living Docs Sync & ADR Ingestion',
    status: 'COMPLETED',
    progressPct: 100,
    activeArtifact: 'ADR-0043 Synchronized',
  },
  {
    role: 'release_agent',
    displayName: 'Release Agent',
    avatar: '🚀',
    currentTask: 'Istio 90/10 Canary Split Monitoring',
    status: 'WORKING',
    progressPct: 85,
    activeArtifact: 'Canary Health 100%',
  },
];

export const MOCK_AUTONOMOUS_TASKS: AutonomousTaskItem[] = [
  {
    id: 'task-1',
    title: 'Refactor Monolithic Analysis Service & SQL Injection Patch',
    description: 'Decompose monolithic class methods to reduce cyclomatic complexity from 18.4 to 4.2 and introduce parameterized SQLAlchemy statements.',
    category: 'Refactoring & Security',
    requiresApproval: true,
    approvalState: 'AWAITING',
    filesAffected: ['apps/backend/app/services/analysis_service.py', 'apps/backend/app/api/v1/repositories.py'],
    estimatedEffortHours: 4,
    aiConfidencePct: 96.5,
    prLink: 'https://github.com/codeatlas/codeatlas/pull/482',
  },
  {
    id: 'task-2',
    title: 'Generate Pytest Suite with 90%+ Edge Case Coverage',
    description: 'Add 42 unit and integration tests covering concurrent database connections and Redis cache eviction fallbacks.',
    category: 'Testing',
    requiresApproval: true,
    approvalState: 'APPROVED',
    filesAffected: ['tests/test_analysis_service.py', 'tests/test_api_endpoints.py'],
    estimatedEffortHours: 3,
    aiConfidencePct: 98.0,
  },
];

export const MOCK_WORKFLOW_HISTORY: WorkflowHistoryRecord[] = [
  {
    id: 'hist-1',
    workflowName: 'Investigate Production Incident (SEV-1)',
    startTime: 'Today, 09:00 AM',
    endTime: 'Today, 09:12 AM',
    duration: '12 mins',
    agentsUsed: ['security_agent', 'performance_agent', 'simulation_agent'],
    repository: 'CodeAtlas / PaymentService',
    actionsCount: 8,
    artifactsGenerated: ['Incident Postmortem Report', 'Istio Canary Route Config'],
    approvalStatus: 'APPROVED',
    status: 'COMPLETED',
  },
  {
    id: 'hist-2',
    workflowName: 'Prepare Release Candidate v4.8.0-rc2',
    startTime: 'Today, 11:20 AM',
    endTime: 'Today, 11:30 AM',
    duration: '10 mins',
    agentsUsed: ['release_agent', 'forecast_agent'],
    repository: 'CodeAtlas / Monorepo',
    actionsCount: 6,
    artifactsGenerated: ['Release Scorecard 96/100', 'Rollback MTTR Plan'],
    approvalStatus: 'AUTO_EXECUTED',
    status: 'COMPLETED',
  },
];

export const MOCK_INTER_SYSTEM_LINKS: InterSystemLink[] = [
  { subsystem: 'mission_control', label: 'AI Mission Control', url: '/command-center', badge: 'Command' },
  { subsystem: 'cto_workspace', label: 'AI CTO Workspace', url: '/ai-cto', badge: 'CTO' },
  { subsystem: 'investigation_engine', label: 'AI Investigation Engine', url: '/investigate', badge: 'Root Cause' },
  { subsystem: 'refactoring_planner', label: 'AI Refactoring Planner', url: '/improve', badge: 'Refactor' },
  { subsystem: 'doc_engineer', label: 'AI Doc Engineer', url: '/docs', badge: 'Docs' },
  { subsystem: 'code_review', label: 'AI Code Review Intelligence', url: '/review', badge: 'Review' },
  { subsystem: 'release_intelligence', label: 'AI Release Intelligence', url: '/release', badge: 'Release' },
  { subsystem: 'engineering_forecasting', label: 'AI Engineering Forecasting', url: '/forecast', badge: 'Forecast' },
  { subsystem: 'repository_explorer', label: 'Repository Explorer', url: '/repositories', badge: 'AST' },
  { subsystem: 'architecture_intelligence', label: 'Architecture Intelligence', url: '/architecture', badge: 'Topology' },
  { subsystem: 'dependency_intelligence', label: 'Dependency Intelligence', url: '/dependency-graph', badge: 'Graph' },
  { subsystem: 'knowledge_graph', label: 'Knowledge Graph', url: '/knowledge', badge: 'Neo4j' },
  { subsystem: 'simulation_studio', label: 'Simulation Studio', url: '/simulate', badge: 'Monte Carlo' },
  { subsystem: 'monitoring', label: 'Real-Time Monitoring', url: '/monitor', badge: 'Datadog' },
  { subsystem: 'software_memory', label: 'Software Memory Engine', url: '/memory', badge: 'Memory' },
  { subsystem: 'copilot', label: 'AI Copilot', url: '/search', badge: 'Copilot' },
];
