'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Layers,
  ArrowRight,
  CheckCircle2,
  Clock,
  Play,
  Pause,
  RotateCcw,
  Sparkles,
  UserPlus,
  Bookmark,
  Share2,
  ChevronRight,
  ShieldCheck,
  Check
} from 'lucide-react';
import { Button } from '@/components/ui/button';

export interface RoadmapStep {
  id: number;
  title: string;
  subtitle: string;
  status: 'COMPLETED' | 'IN_PROGRESS' | 'PENDING';
  assignedTo: string;
  estimatedTime: string;
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH';
  details: string;
  validationCheck: string;
}

const DEFAULT_STEPS: RoadmapStep[] = [
  {
    id: 1,
    title: 'Extract Service DAL Interface',
    subtitle: 'Decouple raw REST router SQL queries into PaymentsRepository',
    status: 'COMPLETED',
    assignedTo: 'Alex Mercer',
    estimatedTime: '2 hrs',
    riskLevel: 'LOW',
    details: 'Create app/payments/dal.py PaymentsRepository class and wrap inline SQL queries in parameterized methods.',
    validationCheck: 'AST symbol tree validates zero direct database handle imports in router.py'
  },
  {
    id: 2,
    title: 'Move Shared Domain Logic',
    subtitle: 'Relocate Stripe webhook event handling to domain service',
    status: 'IN_PROGRESS',
    assignedTo: 'Sarah Chen',
    estimatedTime: '4 hrs',
    riskLevel: 'MEDIUM',
    details: 'Migrate process_stripe_webhook_event() into domain service module to enforce clean layer boundaries.',
    validationCheck: 'Unit tests confirm 100% coverage on webhook event state transitions'
  },
  {
    id: 3,
    title: 'Update Module Dependencies',
    subtitle: 'Deploy Redis write-through token validation cache',
    status: 'PENDING',
    assignedTo: 'DevOps Agent',
    estimatedTime: '3 hrs',
    riskLevel: 'LOW',
    details: 'Integrate Redis L2 write-through cache pool to eliminate DB connection lock contention under 50k QPS.',
    validationCheck: 'Redis ping latency sub-1ms verified'
  },
  {
    id: 4,
    title: 'Run Digital Twin Load Simulation',
    subtitle: 'Simulate 50,000 QPS burst traffic scenario',
    status: 'PENDING',
    assignedTo: 'Alex Mercer',
    estimatedTime: '30 mins',
    riskLevel: 'LOW',
    details: 'Execute Digital Twin load stress simulation to confirm P99 latency drops from 57ms to 11.4ms.',
    validationCheck: 'Simulation scenario passes 99.99% SLA'
  },
  {
    id: 5,
    title: 'Validate Automated Test Suite',
    subtitle: 'Run 142 AST boundary & integration test assertions',
    status: 'PENDING',
    assignedTo: 'Sarah Chen',
    estimatedTime: '1 hr',
    riskLevel: 'LOW',
    details: 'Run full regression test suite across core monorepo packages.',
    validationCheck: 'Zero test failures or deprecation warnings'
  },
  {
    id: 6,
    title: 'Deploy Automated Refactoring PR',
    subtitle: 'Merge PR #145 with zero-downtime rolling update',
    status: 'PENDING',
    assignedTo: 'Alex Mercer',
    estimatedTime: '15 mins',
    riskLevel: 'LOW',
    details: 'Merge autogenerated refactoring PR into main branch with SOC2 audit clearance.',
    validationCheck: 'Canary deployment passes health checks'
  }
];

export function AiRefactoringRoadmap() {
  const [steps, setSteps] = useState<RoadmapStep[]>(DEFAULT_STEPS);
  const [activeStepId, setActiveStepId] = useState<number>(2);
  const [isScrubberPaused, setIsScrubberPaused] = useState<boolean>(false);

  const toggleStepStatus = (id: number) => {
    setSteps((prev) =>
      prev.map((s) => {
        if (s.id === id) {
          const nextStatus = s.status === 'COMPLETED' ? 'PENDING' : s.status === 'PENDING' ? 'IN_PROGRESS' : 'COMPLETED';
          return { ...s, status: nextStatus };
        }
        return s;
      })
    );
  };

  const completedCount = steps.filter((s) => s.status === 'COMPLETED').length;
  const progressPercent = Math.round((completedCount / steps.length) * 100);

  const activeStep = steps.find((s) => s.id === activeStepId) || steps[1];

  return (
    <div className="glass-card rounded-3xl p-6 border border-slate-800/80 shadow-2xl space-y-5 font-sans select-none">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800/80 pb-4 font-mono">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-cyan-500/10 border border-cyan-500/30 text-cyan-400 flex items-center justify-center">
            <Layers className="w-5 h-5 animate-pulse" />
          </div>
          <div>
            <h3 className="text-base font-black text-white flex items-center gap-2">
              Interactive 6-Step Refactoring Roadmap
            </h3>
            <p className="text-xs text-slate-400 font-sans">
              Sequential engineering execution pipeline enforcing dependency order, risk checks, and validation steps.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3 font-mono text-xs">
          <span className="text-cyan-300 font-bold bg-cyan-500/10 px-3 py-1 rounded-full border border-cyan-500/20">
            {progressPercent}% Complete ({completedCount}/6 Steps)
          </span>

          <Button
            size="sm"
            variant="outline"
            onClick={() => setIsScrubberPaused((p) => !p)}
            className="h-8 text-xs font-mono font-bold bg-slate-900 border-slate-800 text-slate-300 hover:text-white rounded-xl gap-1 cursor-pointer"
          >
            {isScrubberPaused ? <Play className="w-3.5 h-3.5 text-emerald-400" /> : <Pause className="w-3.5 h-3.5 text-amber-400" />}
            {isScrubberPaused ? 'Resume Timeline' : 'Pause Timeline'}
          </Button>
        </div>
      </div>

      {/* Overall Progress Bar */}
      <div className="space-y-1 font-mono">
        <div className="w-full bg-slate-950 h-2.5 rounded-full overflow-hidden border border-slate-800/80 p-0.5">
          <motion.div
            initial={{ width: 0 }}
            animate={{ width: `${progressPercent}%` }}
            transition={{ duration: 0.5 }}
            className="bg-gradient-to-r from-cyan-500 via-indigo-500 to-emerald-500 h-full rounded-full"
          />
        </div>
      </div>

      {/* 6 Step Visual Scrubber Flow */}
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-6 gap-2 font-mono text-xs">
        {steps.map((step) => {
          const isSelected = step.id === activeStepId;
          const isDone = step.status === 'COMPLETED';
          const isInProgress = step.status === 'IN_PROGRESS';

          return (
            <button
              key={step.id}
              onClick={() => setActiveStepId(step.id)}
              className={`p-3 rounded-2xl border transition-all duration-200 text-left space-y-1.5 cursor-pointer relative ${
                isSelected
                  ? 'bg-gradient-to-b from-cyan-500/20 to-indigo-500/20 border-cyan-500/50 text-white shadow-lg'
                  : isDone
                  ? 'bg-slate-950/80 border-slate-800 text-slate-300'
                  : 'bg-slate-950/40 border-slate-900 text-slate-500'
              }`}
            >
              <div className="flex items-center justify-between text-[10px]">
                <span className="font-extrabold uppercase text-cyan-400">STEP {step.id}</span>
                {isDone ? (
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                ) : isInProgress ? (
                  <span className="w-2 h-2 rounded-full bg-cyan-400 animate-ping" />
                ) : (
                  <span className="w-2 h-2 rounded-full bg-slate-800" />
                )}
              </div>

              <div className="font-extrabold text-xs leading-snug line-clamp-1">{step.title}</div>
              <div className="text-[9px] text-slate-400 font-sans truncate">{step.assignedTo}</div>
            </button>
          );
        })}
      </div>

      {/* Active Step Details Panel */}
      <div className="p-5 rounded-2xl bg-slate-950/90 border border-slate-800 space-y-4 font-mono text-xs">
        <div className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-800 pb-3">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="px-2.5 py-0.5 rounded bg-cyan-500/10 border border-cyan-500/30 text-cyan-300 font-bold text-[10px] uppercase">
                STEP {activeStep.id} EXECUTION SPECIFICATION
              </span>
              <span
                className={`text-[9px] font-black uppercase px-2 py-0.5 rounded ${
                  activeStep.status === 'COMPLETED'
                    ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/30'
                    : activeStep.status === 'IN_PROGRESS'
                    ? 'bg-cyan-500/10 text-cyan-400 border border-cyan-500/30'
                    : 'bg-slate-900 text-slate-500 border border-slate-800'
                }`}
              >
                {activeStep.status.replace('_', ' ')}
              </span>
            </div>

            <h3 className="text-base font-black text-white">{activeStep.title}</h3>
            <p className="text-xs text-slate-400 font-sans">{activeStep.subtitle}</p>
          </div>

          <div className="text-right">
            <span className="text-xs font-bold text-slate-300 block">Est. Time: {activeStep.estimatedTime}</span>
            <span className="text-[10px] text-cyan-400">Assigned: {activeStep.assignedTo}</span>
          </div>
        </div>

        <p className="text-xs text-slate-300 font-sans leading-relaxed">{activeStep.details}</p>

        {/* Validation Check */}
        <div className="p-3 bg-slate-900 rounded-xl border border-slate-800 space-y-1">
          <span className="text-[10px] text-slate-500 uppercase font-bold block flex items-center gap-1">
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" /> SUCCESS VALIDATION CHECK:
          </span>
          <span className="text-emerald-300 text-xs font-mono">{activeStep.validationCheck}</span>
        </div>

        {/* Action Controls */}
        <div className="flex justify-end gap-2 pt-2 border-t border-slate-800">
          <Button
            size="sm"
            variant="outline"
            onClick={() => toggleStepStatus(activeStep.id)}
            className="h-8 text-xs font-bold bg-slate-900 border-slate-800 text-slate-200 hover:text-white rounded-xl gap-1 cursor-pointer"
          >
            <Check className="w-3.5 h-3.5 text-emerald-400" />
            {activeStep.status === 'COMPLETED' ? 'Mark Incomplete' : 'Mark Step Complete'}
          </Button>
        </div>
      </div>
    </div>
  );
}
