'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import Link from 'next/link';
import {
  CheckCircle2,
  Clock,
  Flame,
  ArrowUpRight,
  UserPlus,
  XCircle,
  Sparkles,
  Sliders,
  AlertTriangle,
  Play,
  Brain,
  Layers,
  FileText,
  UserCheck
} from 'lucide-react';
import { Button } from '@/components/ui/button';

export interface FocusTask {
  id: string;
  title: string;
  repository: string;
  priority: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
  estimatedEffort: string;
  businessImpact: string;
  category: string;
  targetUrl: string;
  assignedTo?: string;
  status: 'PENDING' | 'IN_PROGRESS' | 'DONE';
  description: string;
}

const INITIAL_TASKS: FocusTask[] = [
  {
    id: 'task-1',
    title: 'Review REST Router Architecture Drift in Payment Service',
    repository: 'codeatlas/payments-service',
    priority: 'CRITICAL',
    estimatedEffort: '2 hrs (~14 files)',
    businessImpact: '$18.5k/yr Debt Payoff',
    category: 'Architecture',
    targetUrl: '/investigate',
    assignedTo: 'Alex Mercer',
    status: 'PENDING',
    description: 'Inline raw SQL queries in handler functions bypass repository abstraction layer and prevent Redis caching.'
  },
  {
    id: 'task-2',
    title: 'Resolve High-Risk Token Validation Lock Contention in Auth Gateway',
    repository: 'codeatlas/auth-gateway',
    priority: 'HIGH',
    estimatedEffort: '4 hrs',
    businessImpact: '+350% Ingress Throughput',
    category: 'Performance',
    targetUrl: '/improve',
    assignedTo: 'Unassigned',
    status: 'IN_PROGRESS',
    description: 'Integrate Redis L2 write-through caching layer to eliminate DB connection lock spikes under 50k req/sec traffic.'
  },
  {
    id: 'task-3',
    title: 'Approve AI Recommendation: Decouple Analytics Stream Consumers',
    repository: 'codeatlas/analytics-pipeline',
    priority: 'HIGH',
    estimatedEffort: '30 mins',
    businessImpact: '34% Latency Reduction',
    category: 'Simulation',
    targetUrl: '/simulate',
    assignedTo: 'Alex Mercer',
    status: 'PENDING',
    description: 'Approve autogenerated Kubernetes deployment patch for Kafka microservices split.'
  },
  {
    id: 'task-4',
    title: 'Upgrade Deprecated Pydantic V1 Config Objects',
    repository: 'codeatlas/analytics-pipeline',
    priority: 'MEDIUM',
    estimatedEffort: '1 hr',
    businessImpact: 'Zero Deprecation Warnings',
    category: 'Code Hygiene',
    targetUrl: '/improve',
    assignedTo: 'Unassigned',
    status: 'PENDING',
    description: 'Update BaseSettings import to pydantic-settings module across worker pool services.'
  },
  {
    id: 'task-5',
    title: 'Review Documentation Coverage in Checkout API Module',
    repository: 'codeatlas/payments-service',
    priority: 'LOW',
    estimatedEffort: '45 mins',
    businessImpact: 'Maintainability',
    category: 'Documentation',
    targetUrl: '/knowledge',
    assignedTo: 'Unassigned',
    status: 'PENDING',
    description: 'Generate ADR documentation for payment processing error recovery handlers.'
  }
];

export function TodaysFocusTasks() {
  const [tasks, setTasks] = useState<FocusTask[]>(INITIAL_TASKS);
  const [assigningTaskId, setAssigningTaskId] = useState<string | null>(null);

  const toggleTaskStatus = (taskId: string) => {
    setTasks((prev) =>
      prev.map((t) => {
        if (t.id === taskId) {
          const nextStatus = t.status === 'DONE' ? 'PENDING' : t.status === 'PENDING' ? 'IN_PROGRESS' : 'DONE';
          return { ...t, status: nextStatus };
        }
        return t;
      })
    );
  };

  const dismissTask = (taskId: string) => {
    setTasks((prev) => prev.filter((t) => t.id !== taskId));
  };

  const assignTask = (taskId: string, assignee: string) => {
    setTasks((prev) =>
      prev.map((t) => (t.id === taskId ? { ...t, assignedTo: assignee } : t))
    );
    setAssigningTaskId(null);
  };

  const pendingCount = tasks.filter((t) => t.status !== 'DONE').length;

  return (
    <div className="glass-card rounded-3xl p-6 border border-slate-800/80 shadow-2xl space-y-5 font-sans select-none">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800/80 pb-4 font-mono">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-400 flex items-center justify-center">
            <Sliders className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-base font-black text-white flex items-center gap-2">
              Today's Focus Task List
            </h2>
            <p className="text-xs text-slate-400 font-sans">
              AI prioritized action items ranked by business impact, risk score, and technical urgency.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <span className="px-3 py-1 bg-amber-500/10 text-amber-400 border border-amber-500/20 text-xs font-bold rounded-full">
            {pendingCount} Tasks Pending Attention
          </span>
        </div>
      </div>

      {/* Task List */}
      <div className="space-y-3">
        <AnimatePresence>
          {tasks.map((task) => (
            <motion.div
              key={task.id}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, x: -16 }}
              transition={{ duration: 0.2 }}
              className={`p-4 rounded-2xl border transition-all duration-200 space-y-3 ${
                task.status === 'DONE'
                  ? 'bg-slate-950/40 border-slate-900 opacity-60'
                  : task.priority === 'CRITICAL'
                  ? 'bg-slate-900/90 border-rose-500/30 hover:border-rose-500/50'
                  : 'bg-slate-950/80 border-slate-800 hover:border-cyan-500/40'
              }`}
            >
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-start gap-3">
                  {/* Status Checkbox */}
                  <button
                    onClick={() => toggleTaskStatus(task.id)}
                    className="mt-0.5 text-slate-400 hover:text-cyan-400 transition-colors"
                  >
                    <CheckCircle2
                      className={`w-5 h-5 ${
                        task.status === 'DONE'
                          ? 'text-emerald-400 fill-emerald-500/20'
                          : task.status === 'IN_PROGRESS'
                          ? 'text-cyan-400 animate-pulse'
                          : 'text-slate-600'
                      }`}
                    />
                  </button>

                  <div className="space-y-1">
                    <div className="flex items-center gap-2 font-mono text-xs">
                      <span
                        className={`px-2 py-0.5 rounded text-[9px] font-black uppercase ${
                          task.priority === 'CRITICAL'
                            ? 'bg-rose-500/10 text-rose-400 border border-rose-500/30'
                            : task.priority === 'HIGH'
                            ? 'bg-amber-500/10 text-amber-400 border border-amber-500/30'
                            : 'bg-cyan-500/10 text-cyan-400 border border-cyan-500/30'
                        }`}
                      >
                        {task.priority}
                      </span>
                      <span className="text-slate-400">{task.repository}</span>
                    </div>

                    <h3
                      className={`font-bold text-sm ${
                        task.status === 'DONE' ? 'line-through text-slate-500' : 'text-white'
                      }`}
                    >
                      {task.title}
                    </h3>
                  </div>
                </div>

                {/* Business Impact Badge */}
                <div className="text-right font-mono shrink-0">
                  <span className="text-xs font-black text-emerald-400 block">{task.businessImpact}</span>
                  <span className="text-[10px] text-slate-500">Effort: {task.estimatedEffort}</span>
                </div>
              </div>

              <p className="text-xs text-slate-400 font-sans leading-relaxed pl-8">
                {task.description}
              </p>

              {/* Task Footer Actions */}
              <div className="flex flex-wrap items-center justify-between gap-2 pt-2 border-t border-slate-800/60 pl-8 font-mono text-xs">
                <div className="flex items-center gap-3 text-slate-400 text-[11px]">
                  <span>Assignee: <strong className="text-cyan-300">{task.assignedTo || 'Unassigned'}</strong></span>
                  <button
                    onClick={() => setAssigningTaskId(task.id)}
                    className="text-slate-500 hover:text-white flex items-center gap-1 text-[10px]"
                  >
                    <UserPlus className="w-3 h-3 text-indigo-400" /> Reassign
                  </button>
                </div>

                <div className="flex items-center gap-2">
                  <Link href={task.targetUrl}>
                    <Button
                      size="sm"
                      className="h-7 text-[11px] font-bold bg-cyan-600 hover:bg-cyan-500 text-white rounded-xl gap-1 cursor-pointer"
                    >
                      Open Directly <ArrowUpRight className="w-3.5 h-3.5" />
                    </Button>
                  </Link>

                  <button
                    onClick={() => dismissTask(task.id)}
                    className="p-1 text-slate-500 hover:text-slate-300 transition-colors"
                    title="Dismiss Task"
                  >
                    <XCircle className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {/* Assignee Modal / Dropdown overlay */}
              {assigningTaskId === task.id && (
                <div className="p-3 bg-slate-900 border border-slate-800 rounded-xl space-y-2 font-mono text-xs">
                  <span className="text-slate-400 font-bold block text-[10px]">SELECT ASSIGNEE:</span>
                  <div className="flex flex-wrap gap-2">
                    {['Alex Mercer', 'Sarah Chen', 'DevOps Automated Agent', 'Unassigned'].map((name) => (
                      <button
                        key={name}
                        onClick={() => assignTask(task.id, name)}
                        className="px-2.5 py-1 bg-slate-950 hover:bg-cyan-500/20 text-slate-200 border border-slate-800 rounded-lg text-[11px] font-bold"
                      >
                        {name}
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </motion.div>
          ))}
        </AnimatePresence>
      </div>
    </div>
  );
}
