import {
  ForecastScorecard,
  RiskRadarItem,
  WhatIfScenarioOption,
  ForecastReport,
  PredictiveTrendPoint,
  InterSystemLink,
} from './forecast-types';

export const MOCK_FORECAST_SCORECARD: ForecastScorecard = {
  engineeringHealthScore: 92,
  architectureStabilityScore: 94,
  techDebtAccumulationHours: 34,
  repositoryGrowthLoc: 42000,
  securityRiskCount: 2,
  performanceP95Ms: 24.2,
  deploymentSuccessPct: 98.2,
  developerProductivityGainPct: 15.4,
  maintenanceCostMonthlyUsd: 12400,
  repositoryComplexityScore: 14.2,
};

export const MOCK_RISK_RADAR_ITEMS: RiskRadarItem[] = [
  {
    id: 'radar-1',
    category: 'architecture',
    title: 'Monolithic Database Write IOPS Saturation Risk',
    probabilityPct: 84.2,
    confidencePct: 96.0,
    impactLevel: 'CRITICAL',
    estimatedTimelineDays: 45,
    evidence: 'PostgreSQL primary write IOPS growing at 14.2% month-over-month. Projected write saturation at 100k QPS peak in 45 days.',
    businessImpact: 'Risk of checkout page downtime resulting in estimated $140k/hr revenue loss during traffic surges.',
    engineeringImpact: 'Requires database connection pool tuning, table partition migrations, or PostgreSQL read/write splitting.',
    recommendedAction: 'Apply Alembic 0043 partition migration and introduce Redis write buffer queue.',
    alternativeStrategies: [
      'Option A: Decouple via Kafka Event Bus & Write-Behind Cache',
      'Option B: Upgrade AWS RDS Aurora instance size to db.r6g.4xlarge',
    ],
    estimatedCostUsd: 1200,
    estimatedEffortHours: 24,
    simulationLink: '/simulate',
  },
  {
    id: 'radar-2',
    category: 'security',
    title: 'PyYAML Package Vulnerability Window Opening',
    probabilityPct: 72.0,
    confidencePct: 98.5,
    impactLevel: 'HIGH',
    estimatedTimelineDays: 14,
    evidence: 'Dependabot flagged PyYAML 5.3.1 RCE vulnerability in background ingestion worker.',
    businessImpact: 'Potential unauthorized remote code execution on worker pods.',
    engineeringImpact: 'Upgrade package constraint in pyproject.toml to PyYAML >= 6.0.',
    recommendedAction: 'Execute automated dependency refactoring PR via AI Refactoring Planner.',
    alternativeStrategies: ['Option A: Immediate PyYAML package patch upgrade'],
    estimatedCostUsd: 0,
    estimatedEffortHours: 2,
    simulationLink: '/improve',
  },
  {
    id: 'radar-3',
    category: 'performance',
    title: 'Redis L2 Cache Memory Pressure Eviction Alert',
    probabilityPct: 65.4,
    confidencePct: 94.0,
    impactLevel: 'MEDIUM',
    estimatedTimelineDays: 30,
    evidence: 'Redis cluster memory utilization reaching 88.1%. Key eviction rate increasing by 4.2% daily.',
    businessImpact: 'Cache miss fallback spikes API latency from 24ms to 340ms.',
    engineeringImpact: 'Adjust key TTL policies and scale Redis cluster RAM from 16GB to 32GB.',
    recommendedAction: 'Update Terraform Redis instance spec.',
    alternativeStrategies: ['Option A: Scale Redis Memory', 'Option B: Implement Compact Binary Protobuf Serialization'],
    estimatedCostUsd: 180,
    estimatedEffortHours: 4,
    simulationLink: '/health',
  },
  {
    id: 'radar-4',
    category: 'scalability',
    title: 'Auth Router Token Verification Bottleneck at 45k QPS',
    probabilityPct: 58.0,
    confidencePct: 92.0,
    impactLevel: 'HIGH',
    estimatedTimelineDays: 90,
    evidence: 'CPU utilization on Auth Router pods reaching 78% under 28k QPS stress testing.',
    businessImpact: 'Prevents user onboarding under peak marketing campaigns.',
    engineeringImpact: 'Migrate RS256 token verification to WebAssembly or Rust native extension module.',
    recommendedAction: 'Refactor auth middleware to async Rust NAPI extension.',
    alternativeStrategies: ['Option A: Rust NAPI module', 'Option B: Scale Kubernetes Auth Replicas x3'],
    estimatedCostUsd: 400,
    estimatedEffortHours: 40,
    simulationLink: '/simulate',
  },
  {
    id: 'radar-5',
    category: 'maintainability',
    title: 'Payment Microservice Technical Debt Accumulation',
    probabilityPct: 82.0,
    confidencePct: 95.0,
    impactLevel: 'HIGH',
    estimatedTimelineDays: 60,
    evidence: 'Cyclomatic complexity score 18.4 in PaymentService. 42 hours of technical debt recorded.',
    businessImpact: 'Increases bug rate during feature additions by 35%.',
    engineeringImpact: 'Decompose monolithic class into strategy pattern handlers.',
    recommendedAction: 'Trigger AI Refactoring Planner plan for PaymentService.',
    alternativeStrategies: ['Option A: Execute AI Refactoring Plan'],
    estimatedCostUsd: 0,
    estimatedEffortHours: 18,
    simulationLink: '/tech-debt',
  },
];

export const MOCK_WHAT_IF_SCENARIOS: WhatIfScenarioOption[] = [
  {
    id: 'scen-1',
    question: 'What if traffic doubles to 100,000 QPS?',
    category: 'scaling',
    sideBySideOutcome: [
      { metric: 'P95 API Latency', currentBaseline: '24.2 ms', simulatedFuture: '142.5 ms', impactDelta: '+488%', isPositive: false },
      { metric: 'Database CPU Utilization', currentBaseline: '34.2%', simulatedFuture: '92.4%', impactDelta: '+170%', isPositive: false },
      { metric: 'Monthly Cloud Infrastructure Cost', currentBaseline: '$4,820 / mo', simulatedFuture: '$9,640 / mo', impactDelta: '+$4,820', isPositive: false },
      { metric: 'Deployment Success Probability', currentBaseline: '98.2%', simulatedFuture: '94.0%', impactDelta: '-4.2%', isPositive: false },
    ],
    aiRecommendation: 'Introduce Redis write-behind caching and enable Kubernetes Horizontal Pod Autoscaler (HPA) targeting 65% CPU.',
    confidencePct: 96.4,
  },
  {
    id: 'scen-2',
    question: 'What if we split PaymentService into 3 microservices?',
    category: 'architecture',
    sideBySideOutcome: [
      { metric: 'Domain Layer Isolation', currentBaseline: '87.0%', simulatedFuture: '100.0%', impactDelta: '+13.0%', isPositive: true },
      { metric: 'Maintainability Index', currentBaseline: '42.0', simulatedFuture: '88.5', impactDelta: '+46.5', isPositive: true },
      { metric: 'Deployment Complexity', currentBaseline: 'Low (Monolith)', simulatedFuture: 'Medium (3 Pods)', impactDelta: '+2 Pods', isPositive: false },
      { metric: 'Technical Debt Hours', currentBaseline: '42 Hours', simulatedFuture: '12 Hours', impactDelta: '-30 Hours', isPositive: true },
    ],
    aiRecommendation: 'PROCEED WITH SPLIT. Decomposing PaymentService eliminates 30 hours of tech debt and achieves 100% domain isolation.',
    confidencePct: 98.2,
  },
  {
    id: 'scen-3',
    question: 'What if Redis L2 Cache Cluster fails completely?',
    category: 'infrastructure',
    sideBySideOutcome: [
      { metric: 'PostgreSQL Read IOPS', currentBaseline: '1,420 IOPS', simulatedFuture: '18,400 IOPS', impactDelta: '+1,195%', isPositive: false },
      { metric: 'API P95 Latency', currentBaseline: '24.2 ms', simulatedFuture: '380.0 ms', impactDelta: '+1,470%', isPositive: false },
      { metric: 'Circuit Breaker Status', currentBaseline: 'CLOSED (Normal)', simulatedFuture: 'TRIPPED (Fallback)', impactDelta: 'Tripped', isPositive: false },
    ],
    aiRecommendation: 'Verify multi-region Redis cluster failover and ensure local memory L1 cache retains 5-minute fallback buffer.',
    confidencePct: 99.1,
  },
];

export const MOCK_FORECAST_REPORTS: ForecastReport[] = [
  {
    id: 'rep-1',
    reportType: 'weekly_engineering',
    title: 'Weekly AI Engineering & Architecture Forecast (Week 32, 2026)',
    period: 'Aug 6 - Aug 13, 2026',
    createdAt: 'Today, 06:00 AM',
    executiveSummary: 'Overall repository health is OPTIMAL at 92%. Projected tech debt reduction of 18 hours following PR #482 merge. Zero breaking API changes expected.',
    keyRiskHighlights: [
      'PostgreSQL write IOPS trend projecting 84% saturation within 45 days.',
      'PyYAML CVE package update recommended within 14 days.',
    ],
    strategicActionItems: [
      { task: 'Merge PR #482 Async Checkout Worker', owner: 'Elena Rostova', deadline: 'Aug 8, 2026' },
      { task: 'Upgrade PyYAML to >= 6.0 in pyproject.toml', owner: 'Security Bot', deadline: 'Aug 10, 2026' },
    ],
    projectedMetrics: [
      { metric: 'Health Score', value: '92% -> 94%', trend: 'IMPROVING' },
      { metric: 'Tech Debt', value: '42h -> 24h', trend: 'REDUCING' },
      { metric: 'P95 Latency', value: '340ms -> 24ms', trend: 'OPTIMIZED' },
    ],
  },
  {
    id: 'rep-2',
    reportType: 'monthly_architecture',
    title: 'Monthly Architecture Evolution & Drift Forecast (August 2026)',
    period: 'August 2026',
    createdAt: 'Aug 1, 2026',
    executiveSummary: 'Architecture stability score projected to reach 96% following microservice boundary refactoring.',
    keyRiskHighlights: [
      'Auth Router QPS capacity requiring Rust NAPI extension within 90 days.',
    ],
    strategicActionItems: [
      { task: 'Execute ADR-0042 Graph-Relational hybrid migration', owner: 'Sarah Chen', deadline: 'Aug 25, 2026' },
    ],
    projectedMetrics: [
      { metric: 'Architecture Viability', value: '94%', trend: 'STABLE' },
      { metric: 'Microservices Count', value: '4 -> 6', trend: 'EXPANDING' },
    ],
  },
];

export const MOCK_PREDICTIVE_TRENDS: PredictiveTrendPoint[] = [
  { timeHorizon: 'Today', healthScore: 92, cloudCostUsd: 4820, techDebtHours: 42, qpsCapacity: 18500, microservicesCount: 4 },
  { timeHorizon: '1 Month', healthScore: 94, cloudCostUsd: 5200, techDebtHours: 24, qpsCapacity: 28000, microservicesCount: 4 },
  { timeHorizon: '3 Months', healthScore: 91, cloudCostUsd: 5800, techDebtHours: 31, qpsCapacity: 35000, microservicesCount: 5 },
  { timeHorizon: '6 Months', healthScore: 88, cloudCostUsd: 7400, techDebtHours: 45, qpsCapacity: 45000, microservicesCount: 5 },
  { timeHorizon: '1 Year', healthScore: 85, cloudCostUsd: 9600, techDebtHours: 52, qpsCapacity: 85000, microservicesCount: 6 },
  { timeHorizon: '3 Years', healthScore: 95, cloudCostUsd: 14200, techDebtHours: 12, qpsCapacity: 250000, microservicesCount: 8 },
  { timeHorizon: '5 Years', healthScore: 98, cloudCostUsd: 22000, techDebtHours: 4, qpsCapacity: 650000, microservicesCount: 12 },
];

export const MOCK_INTER_SYSTEM_LINKS: InterSystemLink[] = [
  { subsystem: 'mission_control', label: 'AI Mission Control', url: '/command-center', badge: 'Command' },
  { subsystem: 'cto_workspace', label: 'AI CTO Workspace', url: '/ai-cto', badge: 'CTO' },
  { subsystem: 'investigation_engine', label: 'AI Investigation Engine', url: '/investigate', badge: 'Root Cause' },
  { subsystem: 'refactoring_planner', label: 'AI Refactoring Planner', url: '/improve', badge: 'Refactor' },
  { subsystem: 'doc_engineer', label: 'AI Doc Engineer', url: '/docs', badge: 'Docs' },
  { subsystem: 'code_review', label: 'AI Code Review Intelligence', url: '/review', badge: 'Review' },
  { subsystem: 'release_intelligence', label: 'AI Release Intelligence', url: '/release', badge: 'Release' },
  { subsystem: 'repository_explorer', label: 'Repository Explorer', url: '/repositories', badge: 'AST' },
  { subsystem: 'architecture_intelligence', label: 'Architecture Intelligence', url: '/architecture', badge: 'Topology' },
  { subsystem: 'knowledge_graph', label: 'Knowledge Graph', url: '/knowledge', badge: 'Neo4j' },
  { subsystem: 'simulation_studio', label: 'Simulation Studio', url: '/simulate', badge: 'Monte Carlo' },
  { subsystem: 'monitoring', label: 'Real-Time Monitoring', url: '/monitor', badge: 'Datadog' },
  { subsystem: 'security', label: 'Security Center', url: '/security', badge: 'SOC2' },
  { subsystem: 'tech_debt', label: 'Technical Debt Dashboard', url: '/tech-debt', badge: 'Debt' },
  { subsystem: 'performance', label: 'Performance & Health', url: '/health', badge: 'Metrics' },
  { subsystem: 'software_memory', label: 'Software Memory Engine', url: '/memory', badge: 'Memory' },
];
