"""Add acquisition columns and phases 23-24 tables

Revision ID: 4a97a2694606
Revises: 002_collaboration_schema
Create Date: 2026-09-23 17:59:05.495161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003_git_acquisition_schema'
down_revision: Union[str, None] = '002_collaboration_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependencies', sa.Column('target_file_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_dependencies_target_file_id'), 'dependencies', ['target_file_id'], unique=False)
    op.create_foreign_key(None, 'dependencies', 'files', ['target_file_id'], ['id'], ondelete='SET NULL')
    op.add_column('repositories', sa.Column('clone_path', sa.String(length=1024), nullable=True))
    op.add_column('repositories', sa.Column('acquisition_status', sa.String(length=50), nullable=False, server_default='NOT_CLONED'))
    op.add_column('repositories', sa.Column('acquisition_error', sa.Text(), nullable=True))
    op.add_column('repositories', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_repositories_acquisition_status'), 'repositories', ['acquisition_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repositories_acquisition_status'), table_name='repositories')
    op.drop_column('repositories', 'last_synced_at')
    op.drop_column('repositories', 'acquisition_error')
    op.drop_column('repositories', 'acquisition_status')
    op.drop_column('repositories', 'clone_path')
    op.drop_constraint(None, 'dependencies', type_='foreignkey')
    op.drop_index(op.f('ix_dependencies_target_file_id'), table_name='dependencies')
    op.drop_column('dependencies', 'target_file_id')
    # ### end Alembic commands ###
