import {
  EnterpriseScenarioItem,
  AiBoardroomParticipant,
  ExecutiveDecisionReport,
  ScenarioAdvisorQA,
} from './esl-types';

export const MOCK_ENTERPRISE_SCENARIOS: EnterpriseScenarioItem[] = [
  {
    id: 'scen-a',
    name: 'Scenario A: Baseline Monolith Maintenance',
    category: 'Baseline',
    technicalScore: 78,
    businessScore: 72,
    monthlyCostUsd: 12400,
    p95LatencyMs: 180.0,
    techDebtHours: 42,
    migrationEffortDays: 0,
    riskLevel: 'MEDIUM',
    roiMultiplier: 1.0,
    description: 'Keep current single monolithic database ledgers with vertical EC2 scaling.',
    aiRecommendationNote: 'NOT RECOMMENDED for > 50k QPS peak traffic loads.',
  },
  {
    id: 'scen-b',
    name: 'Scenario B: Microservices gRPC Migration',
    category: 'Architecture',
    technicalScore: 94,
    businessScore: 92,
    monthlyCostUsd: 16800,
    p95LatencyMs: 24.2,
    techDebtHours: 24,
    migrationEffortDays: 45,
    riskLevel: 'MEDIUM',
    roiMultiplier: 3.8,
    description: 'Decouple monolithic domain boundaries into gRPC microservices on AWS EKS.',
    aiRecommendationNote: 'RECOMMENDED for scaling engineering team velocity and independent deployments.',
  },
  {
    id: 'scen-c',
    name: 'Scenario C: Event-Driven Kafka Architecture',
    category: 'Event-Driven',
    technicalScore: 98,
    businessScore: 96,
    monthlyCostUsd: 18500,
    p95LatencyMs: 18.0,
    techDebtHours: 14,
    migrationEffortDays: 30,
    riskLevel: 'LOW',
    roiMultiplier: 4.8,
    description: 'Decouple checkout & billing via Strimzi Kafka event stream with zero data loss.',
    aiRecommendationNote: 'HIGHEST RATED. Best balance of latency reduction, fault isolation, and scalability.',
  },
  {
    id: 'scen-d',
    name: 'Scenario D: Serverless AWS Lambda API Routes',
    category: 'Serverless',
    technicalScore: 89,
    businessScore: 85,
    monthlyCostUsd: 14200,
    p95LatencyMs: 45.0,
    techDebtHours: 10,
    migrationEffortDays: 20,
    riskLevel: 'LOW',
    roiMultiplier: 3.2,
    description: 'Migrate API Gateway endpoints to AWS Lambda with DynamoDB global tables.',
    aiRecommendationNote: 'GOOD FOR VARIABLE TRAFFIC. Mild cold start latency overhead on API routes.',
  },
];

export const MOCK_BOARDROOM_PARTICIPANTS: AiBoardroomParticipant[] = [
  {
    role: 'AI CTO',
    agentName: 'Dr. Elena Vance',
    avatarColor: 'bg-cyan-500',
    statement: 'Scenario C (Event-Driven Kafka Architecture) provides the strongest strategic foundation for our 3-year growth plan, unlocking 4.8x ROI while reducing P95 latency to 18ms.',
    tradeOffSummary: 'Requires initial 30-day team enablement on Kafka partition key design.',
    riskWarning: 'Ensure Strimzi Kafka cluster topic replication factor is set to 3 across AZs.',
    verdict: 'APPROVE',
  },
  {
    role: 'AI Security Architect',
    agentName: 'Marcus Thorne',
    avatarColor: 'bg-purple-500',
    statement: 'Event-Driven decoupling limits blast radius. Istio mTLS STRICT enforcement across Kafka brokers guarantees 100% data-in-transit encryption.',
    tradeOffSummary: 'Requires SOC2 compliance re-audit for event bus log persistence.',
    riskWarning: 'Verify zero PII data leak in Kafka event topic payload schemas.',
    verdict: 'APPROVE',
  },
  {
    role: 'AI Performance Engineer',
    agentName: 'Siddharth Rao',
    avatarColor: 'bg-emerald-500',
    statement: 'P95 response latency drops from 180ms down to 18ms (90% latency reduction). Database write lock contention on PostgreSQL is completely eliminated.',
    tradeOffSummary: 'Requires async event consumer idempotency checks on checkout workers.',
    riskWarning: 'Monitor consumer lag telemetry under 100k QPS surge load.',
    verdict: 'APPROVE',
  },
  {
    role: 'AI FinOps Advisor',
    agentName: 'Claire Du Pont',
    avatarColor: 'bg-amber-500',
    statement: 'Monthly cloud spend increases by +$6,100/mo ($18,500/mo total), but prevents $45,000/mo in lost checkout revenue caused by 504 gateway timeouts.',
    tradeOffSummary: 'Net positive financial ROI within 60 days of deployment.',
    riskWarning: 'Utilize 1-Year Strimzi Kafka Reserved Instances to trim cost by $1,800/mo.',
    verdict: 'APPROVE',
  },
];

export const MOCK_EXECUTIVE_REPORT: ExecutiveDecisionReport = {
  reportId: 'REP-ESL-2026-90',
  title: 'Executive Decision Intelligence Report: Event-Driven Kafka Migration (Scenario C)',
  executiveSummary: 'The AI Boardroom unanimously recommends approving Scenario C (Event-Driven Kafka Architecture). This strategic decision drops P95 checkout latency from 180ms to 18ms, eliminates DB connection pool saturation under 50k QPS, and yields a 4.8x ROI.',
  technicalAnalysis: 'Decouples monolithic payment transactions via Strimzi Kafka topics with Istio mTLS STRICT security and zero data loss durability.',
  businessImpactSummary: 'Eliminates HTTP 504 gateway timeouts during peak sales, protecting an estimated $540,000 in annual revenue.',
  roiProjection: '4.8x Return on Investment within 6 months of production rollout.',
  migrationRoadmapMilestones: [
    { phase: 'Phase 1', title: 'Provision Strimzi Kafka Cluster & Istio Mesh', durationWeeks: 2 },
    { phase: 'Phase 2', title: 'Deploy Dual-Write Event Producer Proxy', durationWeeks: 2 },
    { phase: 'Phase 3', title: 'Shadow Read Benchmarking & Chaos Verification', durationWeeks: 1 },
    { phase: 'Phase 4', title: 'Full Production Traffic Cutover', durationWeeks: 1 },
  ],
  riskRegister: [
    { risk: 'Kafka Consumer Lag under 100k QPS', severity: 'MEDIUM', mitigation: 'Enable Kubernetes HPA on event worker pods.' },
    { risk: 'Schema Evolution Compatibility', severity: 'LOW', mitigation: 'Enforce Confluent Schema Registry Protobuf validation.' },
  ],
};

export const MOCK_SCENARIO_QA: ScenarioAdvisorQA[] = [
  {
    id: 'sqa-1',
    question: 'Which scenario provides the highest Return on Investment (ROI)?',
    answerSummary: 'Scenario C (Event-Driven Kafka Architecture) delivers the highest ROI (4.8x) by dropping checkout latency to 18ms and protecting $540k in annual peak traffic revenue.',
    evidenceTelemetry: 'AI Boardroom unanimous consensus with 98.4% confidence score.',
    confidencePct: 98.4,
  },
  {
    id: 'sqa-2',
    question: 'What are the main trade-offs of Scenario C vs Scenario B?',
    answerSummary: 'Scenario C requires 30 days of migration effort (vs 45 days for Microservices gRPC) and has lower operational complexity while achieving 18ms latency (vs 24.2ms).',
    evidenceTelemetry: 'AST dependency analysis verified 100% decoupling feasibility.',
    confidencePct: 99.2,
  },
];
