import {
  DigitalTwinNode,
  SimulationResult,
  NaturalQueryExample,
} from './twin-types';

export const MOCK_TWIN_NODES: DigitalTwinNode[] = [
  {
    id: 'twin-auth',
    name: 'AuthGatewayController',
    nodeType: 'microservice',
    status: 'active',
    healthScore: 94.0,
    complexityScore: 8.2,
    riskLevel: 'LOW',
    dependencies: ['twin-jwt', 'twin-user', 'twin-redis'],
    consumers: ['twin-router'],
    techDebtUsd: 2100,
    p95LatencyMs: 12.0,
    securityStatus: 'Zero CVEs • SOC2 Compliant',
    ownerTeam: 'Identity Core Team',
    aiSummary: 'OAuth2 JWT authentication gateway handling token validation and session locks.',
    x: 220,
    y: 160,
  },
  {
    id: 'twin-payment',
    name: 'PaymentService',
    nodeType: 'microservice',
    status: 'risk',
    healthScore: 82.0,
    complexityScore: 14.8,
    riskLevel: 'HIGH',
    dependencies: ['twin-user', 'twin-stripe', 'twin-kafka'],
    consumers: ['twin-router'],
    techDebtUsd: 18500,
    p95LatencyMs: 180.0,
    securityStatus: 'Direct REST SQL query coupling',
    ownerTeam: 'Payments Domain Team',
    aiSummary: 'Multi-currency checkout processing pipeline. High complexity due to inline DB calls.',
    x: 480,
    y: 280,
  },
  {
    id: 'twin-postgres',
    name: 'PostgreSQLPrimaryDB',
    nodeType: 'database',
    status: 'active',
    healthScore: 89.0,
    complexityScore: 7.1,
    riskLevel: 'MEDIUM',
    dependencies: [],
    consumers: ['twin-user', 'twin-payment'],
    techDebtUsd: 3400,
    p95LatencyMs: 18.0,
    securityStatus: 'Row-Level Security (RLS) enabled',
    ownerTeam: 'Data Platform Team',
    aiSummary: 'Primary relational datastore supporting transactional ACID workloads.',
    x: 980,
    y: 200,
  },
  {
    id: 'twin-redis',
    name: 'RedisCacheCluster',
    nodeType: 'cache',
    status: 'active',
    healthScore: 98.0,
    complexityScore: 3.2,
    riskLevel: 'LOW',
    dependencies: [],
    consumers: ['twin-auth'],
    techDebtUsd: 0,
    p95LatencyMs: 1.2,
    securityStatus: 'Sentinel TLS enabled',
    ownerTeam: 'DevOps / Infra',
    aiSummary: 'In-memory token cache cluster handling 50k req/sec peak loads.',
    x: 740,
    y: 60,
  },
];

export const MOCK_SIMULATION_RESULTS: SimulationResult[] = [
  {
    id: 'res-traffic-2x',
    scenarioTitle: 'What if traffic doubles to 100,000 QPS?',
    actionType: 'scale',
    architectureComparison: {
      beforeState: 'Monolithic PostgreSQL read/write handling 18.5k QPS with 24.2ms P95 latency.',
      afterState: 'PostgreSQL read replicas added with HPA target set to 65% CPU.',
    },
    riskAnalysis: 'PostgreSQL write IOPS pool connection saturation predicted at 92.4% under 100k QPS.',
    costEstimationUsd: 9640,
    performancePredictionP95: '24.2ms -> 142.5ms (Mitigated to 28ms via Redis cache)',
    securityImpact: '0 Security regressions. All TLS mTLS encryption rules preserved.',
    migrationEffortHours: 16,
    rollbackStrategy: 'Revert Istio VirtualService traffic routing to baseline 50k QPS replicas.',
    aiRecommendation: 'PROCEED WITH REDIS WRITE-BEHIND CACHE. Drops database read IOPS by 84%.',
    confidencePct: 96.4,
  },
  {
    id: 'res-split-payment',
    scenarioTitle: 'What if we split PaymentService into 3 microservices?',
    actionType: 'split',
    architectureComparison: {
      beforeState: 'PaymentService monolith (18.4 cyclomatic complexity, 42h tech debt).',
      afterState: '3 Microservices: PaymentIngress, StripeAdapter, BillingLedgerWorker.',
    },
    riskAnalysis: 'Low risk. Inter-service gRPC protocol eliminates synchronous HTTP blocking.',
    costEstimationUsd: 1200,
    performancePredictionP95: '180ms -> 24.2ms P95 latency drop',
    securityImpact: 'Isolated Stripe API keys inside StripeAdapter boundary.',
    migrationEffortHours: 24,
    rollbackStrategy: 'Helm rollback release to v4.7.9.',
    aiRecommendation: 'PROCEED WITH SPLIT. Eliminates 30 hours of tech debt and achieves 100% domain isolation.',
    confidencePct: 98.2,
  },
];

export const MOCK_NATURAL_QUERIES: NaturalQueryExample[] = [
  { query: 'What happens if we remove Redis?', category: 'Infrastructure', simulationId: 'res-traffic-2x' },
  { query: 'What if traffic doubles to 100,000 QPS?', category: 'Scaling', simulationId: 'res-traffic-2x' },
  { query: 'What if we split PaymentService into 3 microservices?', category: 'Refactoring', simulationId: 'res-split-payment' },
  { query: 'What if PostgreSQL fails?', category: 'Chaos & Failover', simulationId: 'res-traffic-2x' },
  { query: 'What if Kafka is unavailable?', category: 'Infrastructure', simulationId: 'res-split-payment' },
  { query: 'What if we migrate to Kubernetes?', category: 'Cloud', simulationId: 'res-traffic-2x' },
];
