import {
  SystemNode,
  RequestFlowPacket,
  TraceSpan,
  FaultExperiment,
  DistributedScenarioQA,
} from './playground-types';

export const MOCK_SYSTEM_NODES: SystemNode[] = [
  {
    id: 'node-gateway',
    name: 'Kong API Gateway (ingress-gw)',
    nodeType: 'gateway',
    status: 'healthy',
    p95LatencyMs: 4.2,
    qps: 52000,
    errorRatePct: 0.01,
    cpuUsagePct: 24,
    memoryUsagePct: 42,
    dependencies: ['node-auth', 'node-payment'],
    consumers: [],
    ownerTeam: 'Edge Infra Team',
    aiSummary: 'Stateless ingress gateway routing external HTTP REST traffic.',
    x: 100,
    y: 200,
  },
  {
    id: 'node-auth',
    name: 'Auth Router (svc-auth-router)',
    nodeType: 'microservice',
    status: 'healthy',
    p95LatencyMs: 12.0,
    qps: 45000,
    errorRatePct: 0.05,
    cpuUsagePct: 38,
    memoryUsagePct: 54,
    dependencies: ['node-redis'],
    consumers: ['node-gateway'],
    ownerTeam: 'Identity & Security',
    aiSummary: 'Stateless JWT RS256 token verification router with L2 cache lookup.',
    x: 350,
    y: 120,
  },
  {
    id: 'node-payment',
    name: 'Payment Service (svc-payment-core)',
    nodeType: 'microservice',
    status: 'degraded',
    p95LatencyMs: 180.0,
    qps: 18500,
    errorRatePct: 2.4,
    cpuUsagePct: 82,
    memoryUsagePct: 78,
    dependencies: ['node-postgres', 'node-kafka', 'node-stripe'],
    consumers: ['node-gateway'],
    ownerTeam: 'Core Payments Team',
    aiSummary: 'Asynchronous checkout processing pipeline with high DB coupling.',
    x: 350,
    y: 300,
  },
  {
    id: 'node-redis',
    name: 'Redis L2 Cache (cache-redis-primary)',
    nodeType: 'cache',
    status: 'healthy',
    p95LatencyMs: 1.2,
    qps: 48000,
    errorRatePct: 0.0,
    cpuUsagePct: 15,
    memoryUsagePct: 62,
    dependencies: [],
    consumers: ['node-auth'],
    ownerTeam: 'Data Platform',
    aiSummary: 'In-memory token session cache cluster handling 48k QPS.',
    x: 600,
    y: 80,
  },
  {
    id: 'node-postgres',
    name: 'PostgreSQL Relational Primary (db-primary)',
    nodeType: 'database',
    status: 'degraded',
    p95LatencyMs: 24.5,
    qps: 12000,
    errorRatePct: 0.8,
    cpuUsagePct: 88,
    memoryUsagePct: 84,
    dependencies: [],
    consumers: ['node-payment'],
    ownerTeam: 'Database Admins',
    aiSummary: 'Primary ACID database under connection pool saturation pressure.',
    x: 600,
    y: 260,
  },
  {
    id: 'node-kafka',
    name: 'Strimzi Kafka Cluster (kafka-event-bus)',
    nodeType: 'queue',
    status: 'healthy',
    p95LatencyMs: 2.0,
    qps: 34000,
    errorRatePct: 0.0,
    cpuUsagePct: 28,
    memoryUsagePct: 45,
    dependencies: [],
    consumers: ['node-payment'],
    ownerTeam: 'Event Stream Infra',
    aiSummary: 'Distributed event streaming topic bus for checkout events.',
    x: 600,
    y: 420,
  },
];

export const MOCK_REQUEST_PACKETS: RequestFlowPacket[] = [
  { id: 'pkt-1', sourceNodeId: 'node-gateway', targetNodeId: 'node-auth', type: 'api', status: 'success', latencyMs: 12.0 },
  { id: 'pkt-2', sourceNodeId: 'node-auth', targetNodeId: 'node-redis', type: 'cache', status: 'success', latencyMs: 1.2 },
  { id: 'pkt-3', sourceNodeId: 'node-gateway', targetNodeId: 'node-payment', type: 'api', status: 'retry', latencyMs: 180.0 },
  { id: 'pkt-4', sourceNodeId: 'node-payment', targetNodeId: 'node-postgres', type: 'db_query', status: 'failure', latencyMs: 340.0 },
  { id: 'pkt-5', sourceNodeId: 'node-payment', targetNodeId: 'node-kafka', type: 'event', status: 'success', latencyMs: 2.0 },
];

export const MOCK_TRACE_SPANS: TraceSpan[] = [
  {
    id: 'span-root',
    serviceName: 'ingress-gw',
    operationName: 'POST /api/v1/checkout',
    startTimeMs: 0,
    durationMs: 196.2,
    status: 'ok',
    tags: { 'http.status_code': '200', 'component': 'Kong' },
    children: [
      {
        id: 'span-auth',
        serviceName: 'svc-auth-router',
        operationName: 'RS256 Verify Token',
        startTimeMs: 2.1,
        durationMs: 12.0,
        status: 'ok',
        tags: { 'cache.hit': 'true' },
      },
      {
        id: 'span-payment',
        serviceName: 'svc-payment-core',
        operationName: 'Execute Checkout Transaction',
        startTimeMs: 15.4,
        durationMs: 180.0,
        status: 'error',
        tags: { 'db.error': 'ConnectionPoolTimeout', 'retry.count': '2' },
        children: [
          {
            id: 'span-db',
            serviceName: 'db-primary',
            operationName: 'SELECT * FROM users WHERE id = $1 FOR UPDATE',
            startTimeMs: 22.0,
            durationMs: 154.0,
            status: 'error',
            tags: { 'pg.lock_wait_ms': '148' },
          },
        ],
      },
    ],
  },
];

export const MOCK_FAULT_EXPERIMENTS: FaultExperiment[] = [
  {
    id: 'exp-1',
    title: 'Service Crash: Inject Auth Router Pod Failure',
    faultType: 'SERVICE_CRASH',
    targetNodeId: 'node-auth',
    description: 'Kill all 3 replica pods of Auth Router to test API Gateway failover.',
    propagatedImpact: 'Kong Gateway returns HTTP 503 Service Unavailable for 100% of unauthenticated requests.',
    aiCascadingSummary: 'Cascading failure blocked at API Gateway ingress. Zero data corruption on database ledgers.',
  },
  {
    id: 'exp-2',
    title: 'Database Failure: PostgreSQL Master Node Outage',
    faultType: 'DATABASE_FAILURE',
    targetNodeId: 'node-postgres',
    description: 'Simulate primary database failover during peak 50k QPS checkout volume.',
    propagatedImpact: 'PaymentService checkout workers queue failed transactions into Kafka topic for retry.',
    aiCascadingSummary: 'Kafka event bus prevents data loss. Automatic failover to RDS read replica completes in 12.4s.',
  },
];

export const MOCK_DISTRIBUTED_QA: DistributedScenarioQA[] = [
  {
    id: 'dqa-1',
    question: 'What happens if Auth Service fails completely?',
    answerSummary: 'If Auth Service fails, Kong API Gateway intercepts requests and returns HTTP 503. Session token validation drops, but PaymentService data ledgers remain untouched.',
    cascadingNodes: ['node-gateway', 'node-auth'],
    mitigationStrategy: 'Enable local memory L1 fallback cache in Kong Gateway plugins.',
    confidencePct: 98.4,
  },
  {
    id: 'dqa-2',
    question: 'Which service becomes the primary latency bottleneck under 100k QPS?',
    answerSummary: 'PaymentService (svc-payment-core) becomes the primary bottleneck due to synchronous PostgreSQL read connection pool saturation (180ms P95 latency).',
    cascadingNodes: ['node-payment', 'node-postgres'],
    mitigationStrategy: 'Introduce Redis write-behind cache layer and decouple checkout queries via Kafka.',
    confidencePct: 99.2,
  },
];
