import {
  ArchitectureScenario,
  SimulationParameters,
  AdvisorQA,
} from './evo-types';

export const MOCK_DEFAULT_PARAMETERS: SimulationParameters = {
  trafficQps: 50000,
  teamSizeEngineers: 45,
  infraBudgetUsd: 12000,
  deploymentFrequencyPerDay: 8,
  techDebtToleranceHours: 30,
};

export const MOCK_SCENARIOS: ArchitectureScenario[] = [
  {
    id: 'scenario-a',
    name: 'Scenario A: Keep Baseline Monolith',
    category: 'Monolith',
    badge: 'Baseline',
    description: 'Maintain current monolithic structure with vertical database scaling.',
    healthScore: 78.0,
    p95LatencyMs: 180.0,
    monthlyCostUsd: 4200,
    techDebtHours: 42,
    migrationEffortDays: 0,
    incidentProbabilityPct: 18.5,
    developerProductivityScore: 65,
    aiRecommendationScore: 45,
    aiReasoning: 'DB connection locks under peak 100k QPS will cause HTTP 504 timeouts. High technical debt growth.',
  },
  {
    id: 'scenario-b',
    name: 'Scenario B: Move to Microservices',
    category: 'Microservices',
    badge: 'High Scale',
    description: 'Decouple monolithic domain boundaries into gRPC microservices.',
    healthScore: 94.0,
    p95LatencyMs: 24.2,
    monthlyCostUsd: 6800,
    techDebtHours: 24,
    migrationEffortDays: 45,
    incidentProbabilityPct: 4.2,
    developerProductivityScore: 88,
    aiRecommendationScore: 92,
    aiReasoning: 'Eliminates monolithic lock contention. 100% domain isolation across payments, auth, and users.',
  },
  {
    id: 'scenario-c',
    name: 'Scenario C: Event-Driven Architecture',
    category: 'Event-Driven',
    badge: 'Asynchronous',
    description: 'Decouple checkout & billing via Strimzi Kafka distributed event bus.',
    healthScore: 96.5,
    p95LatencyMs: 18.0,
    monthlyCostUsd: 8400,
    techDebtHours: 14,
    migrationEffortDays: 60,
    incidentProbabilityPct: 1.8,
    developerProductivityScore: 94,
    aiRecommendationScore: 98,
    aiReasoning: 'RECOMMENDED FOR HIGH THROUGHPUT. Zero data loss guarantee with asynchronous queuing.',
  },
  {
    id: 'scenario-d',
    name: 'Scenario D: Serverless / FaaS',
    category: 'Serverless',
    badge: 'Cloud Native',
    description: 'Migrate API routes to AWS Lambda with DynamoDB global tables.',
    healthScore: 89.0,
    p95LatencyMs: 45.0,
    monthlyCostUsd: 5200,
    techDebtHours: 10,
    migrationEffortDays: 30,
    incidentProbabilityPct: 6.0,
    developerProductivityScore: 82,
    aiRecommendationScore: 78,
    aiReasoning: 'Excellent cost scaling for variable traffic, but cold start latency spikes affect P95 target.',
  },
  {
    id: 'scenario-e',
    name: 'Scenario E: Modular Monolith',
    category: 'Modular Monolith',
    badge: 'Clean Arch',
    description: 'Enforce strict Hexagonal boundary isolation within monorepo packages.',
    healthScore: 92.0,
    p95LatencyMs: 28.0,
    monthlyCostUsd: 4800,
    techDebtHours: 12,
    migrationEffortDays: 20,
    incidentProbabilityPct: 5.0,
    developerProductivityScore: 90,
    aiRecommendationScore: 88,
    aiReasoning: 'Low migration complexity with 90% of microservice benefits. Highly recommended for 45 engineers.',
  },
  {
    id: 'scenario-f',
    name: 'Scenario F: Domain Driven Design (DDD)',
    category: 'DDD',
    badge: 'Enterprise',
    description: 'Strict Bounded Contexts with CQRS read/write query segregation.',
    healthScore: 95.0,
    p95LatencyMs: 22.0,
    monthlyCostUsd: 5400,
    techDebtHours: 8,
    migrationEffortDays: 35,
    incidentProbabilityPct: 3.5,
    developerProductivityScore: 92,
    aiRecommendationScore: 94,
    aiReasoning: 'Zero architectural drift. AST scanners verify 0 domain leakage across bounded contexts.',
  },
];

export const MOCK_ADVISOR_QA: AdvisorQA[] = [
  {
    id: 'adv-1',
    question: 'Should we migrate to microservices or adoption Event-Driven Architecture?',
    recommendedScenarioId: 'scenario-c',
    answerSummary: 'Event-Driven Architecture (Scenario C) provides the highest AI Recommendation Score (98%) for 50k+ QPS traffic, dropping P95 latency from 180ms to 18ms.',
    evidenceData: 'Kafka Strimzi cluster simulation demonstrates 0 HTTP 504 timeouts under 100k peak load.',
    confidencePct: 98.4,
  },
  {
    id: 'adv-2',
    question: 'Which architectural option has the lowest migration risk and cost?',
    recommendedScenarioId: 'scenario-e',
    answerSummary: 'Modular Monolith (Scenario E) offers the lowest migration effort (20 days) while maintaining low monthly cloud costs ($4,800/mo) and 92.0 health score.',
    evidenceData: 'Monorepo AST isolation clean hexagonal boundary rules verified by Staff AI.',
    confidencePct: 96.8,
  },
];
